import { CfnResource, IAspect, Stack } from "aws-cdk-lib";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as elbv2 from "aws-cdk-lib/aws-elasticloadbalancingv2";
import * as iam from "aws-cdk-lib/aws-iam";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as s3 from "aws-cdk-lib/aws-s3";
import { IConstruct } from "constructs";
import { GUARD_EXCEPTIONS } from "./guard.js";

/**
 * Checkov suppressions. Every entry is an exception agreed with the owner and listed in
 * AGENTS.md; Checkov reads them from `Metadata.checkov.skip`. Findings outside this list must be
 * fixed or agreed first. An asynchronously invoked function must drop `lambdaDlq` and get a DLQ.
 */
export const CHECKOV_EXCEPTIONS = {
  /** Functions only call AWS APIs; a VPC would require NAT or endpoints without benefit. */
  lambdaVpc: {
    id: "CKV_AWS_117",
    comment: "Agreed exception (AGENTS.md): functions only call AWS APIs, no VPC",
  },
  /** Server access log buckets are not logged to themselves nor versioned. */
  logBucketLogging: {
    id: "CKV_AWS_18",
    comment: "Agreed exception (AGENTS.md): access log bucket is not logged to itself",
  },
  logBucketVersioning: {
    id: "CKV_AWS_21",
    comment: "Agreed exception (AGENTS.md): access log bucket expires objects, no versioning",
  },
  /** PoC only (D15): CloudFront reaches the internal ALB through a VPC origin over HTTP. */
  albHttps: {
    id: "CKV_AWS_2",
    comment: "Agreed PoC exception (AGENTS.md, D15): internal ALB behind a CloudFront VPC origin",
  },
  albTls: {
    id: "CKV_AWS_103",
    comment: "Agreed PoC exception (AGENTS.md, D15): internal ALB behind a CloudFront VPC origin",
  },
  /** Every function is invoked synchronously; a DLQ only applies to asynchronous invocations. */
  lambdaDlq: {
    id: "CKV_AWS_116",
    comment: "Agreed exception (AGENTS.md): synchronous invocations only, a DLQ never receives events",
  },
  /** Reserved concurrency breaks installs in accounts with a low concurrency quota. */
  lambdaConcurrency: {
    id: "CKV_AWS_115",
    comment: "Agreed exception (AGENTS.md): customer account quotas are unknown; WAF and Gateway throttle",
  },
  /** PoC only (D15): the default *.cloudfront.net certificate cannot enforce TLSv1.2. */
  cloudfrontTls: {
    id: "CKV_AWS_174",
    comment: "Agreed PoC exception (AGENTS.md, D15): default CloudFront certificate, no custom domain",
  },
  /**
   * The AgentCore managed harness pulls its image with these token APIs (no resource scope).
   * Applies to the agent execution role and to the permissions boundary of agent roles.
   */
  runtimeImageToken: {
    id: "CKV_AWS_107",
    comment: "Agreed exception (AGENTS.md): AgentCore harness image pull, APIs without resource scope",
  },
  /** Role and function generated by the aws-cdk-lib BucketDeployment provider. */
  cdkProviderWrite: {
    id: "CKV_AWS_111",
    comment: "Agreed exception (AGENTS.md): BucketDeployment provider policy generated by aws-cdk-lib",
  },
  cdkProviderEnv: {
    id: "CKV_AWS_173",
    comment: "Agreed exception (AGENTS.md): CDK provider environment holds no secrets (AWS managed key)",
  },
} as const;

type CheckovException = (typeof CHECKOV_EXCEPTIONS)[keyof typeof CHECKOV_EXCEPTIONS];
type CheckovSkip = { id: string; comment: string };

export function suppressCheckov(resource: CfnResource, ...checks: CheckovException[]): void {
  const current = (resource.getMetadata("checkov") as { skip?: CheckovSkip[] } | undefined)?.skip ?? [];
  const merged = new Map<string, CheckovSkip>(current.map((s) => [s.id, s]));
  for (const { id, comment } of checks) merged.set(id, { id, comment });
  resource.addMetadata("checkov", {
    skip: [...merged.values()].sort((a, b) => a.id.localeCompare(b.id)),
  });
}

function guardSuppressed(resource: CfnResource, rule: string): boolean {
  const rules = (resource.getMetadata("guard") as { SuppressedRules?: string[] } | undefined)
    ?.SuppressedRules;
  return rules?.includes(rule) ?? false;
}

function isInternalHttpListener(node: elbv2.CfnListener): boolean {
  const listener = node.node.scope;
  if (node.protocol !== "HTTP" || !(listener instanceof elbv2.ApplicationListener)) return false;
  const lb = listener.loadBalancer.node.defaultChild;
  return lb instanceof elbv2.CfnLoadBalancer && lb.scheme === "internal";
}

function usesDefaultCertificate(stack: Stack, node: cloudfront.CfnDistribution): boolean {
  const config = stack.resolve(node.distributionConfig) as {
    ViewerCertificate?: { CloudFrontDefaultCertificate?: boolean };
  };
  const cert = config.ViewerCertificate;
  return cert === undefined || cert.CloudFrontDefaultCertificate === true;
}

function hasDeadLetterQueue(node: CfnResource): boolean {
  return node instanceof lambda.CfnFunction && node.deadLetterConfig !== undefined;
}

/** Resources created inside the aws-cdk-lib BucketDeployment singleton provider. */
function inBucketDeploymentProvider(node: IConstruct): boolean {
  return node.node.path.includes("/Custom::CDKBucketDeployment");
}

/**
 * Applies the suppressions that follow from resource properties, so new resources stay checked.
 * Log buckets reuse the cfn-guard decision: a bucket is a log bucket if guard already exempts it.
 */
export class CheckovSuppressions implements IAspect {
  visit(node: IConstruct): void {
    if (!(node instanceof CfnResource)) return;
    if (node.cfnResourceType === "AWS::Lambda::Function") {
      // Includes CDK singleton providers (custom resources), which are plain CfnResources.
      suppressCheckov(node, CHECKOV_EXCEPTIONS.lambdaVpc, CHECKOV_EXCEPTIONS.lambdaConcurrency);
      // Asynchronously invoked functions carry a DLQ and stay checked.
      if (!hasDeadLetterQueue(node)) suppressCheckov(node, CHECKOV_EXCEPTIONS.lambdaDlq);
      if (inBucketDeploymentProvider(node)) suppressCheckov(node, CHECKOV_EXCEPTIONS.cdkProviderEnv);
    } else if (node instanceof iam.CfnPolicy && inBucketDeploymentProvider(node)) {
      suppressCheckov(node, CHECKOV_EXCEPTIONS.cdkProviderWrite);
    } else if (
      node instanceof cloudfront.CfnDistribution &&
      usesDefaultCertificate(Stack.of(node), node)
    ) {
      suppressCheckov(node, CHECKOV_EXCEPTIONS.cloudfrontTls);
    } else if (
      node instanceof s3.CfnBucket &&
      guardSuppressed(node, GUARD_EXCEPTIONS.logBucketLogging) &&
      guardSuppressed(node, GUARD_EXCEPTIONS.logBucketVersioning)
    ) {
      suppressCheckov(node, CHECKOV_EXCEPTIONS.logBucketLogging, CHECKOV_EXCEPTIONS.logBucketVersioning);
    } else if (node instanceof elbv2.CfnListener && isInternalHttpListener(node)) {
      suppressCheckov(node, CHECKOV_EXCEPTIONS.albHttps, CHECKOV_EXCEPTIONS.albTls);
    }
  }
}
