import { CfnResource, IAspect, Stack } from "aws-cdk-lib";
import * as ec2 from "aws-cdk-lib/aws-ec2";
import * as lambda from "aws-cdk-lib/aws-lambda";
import * as s3 from "aws-cdk-lib/aws-s3";
import { IConstruct } from "constructs";

/**
 * cfn-guard (AWS Guard Rules Registry, Well-Architected Security Pillar) suppressions.
 * Every suppression is either a rule false positive or an exception agreed with the owner and
 * listed in AGENTS.md; cfn-guard reads them from `Metadata.guard.SuppressedRules`.
 */
export const GUARD_EXCEPTIONS = {
  /** D15: Fargate reaches AWS APIs through public subnets (no NAT) in the PoC. */
  igwRoute: "NO_UNRESTRICTED_ROUTE_TO_IGW",
  /** Functions only call AWS APIs; a VPC would require NAT or endpoints without benefit. */
  lambdaVpc: "LAMBDA_INSIDE_VPC",
  /** Roles generated by CDK custom resource providers. */
  cdkInlinePolicy: "IAM_NO_INLINE_POLICY_CHECK",
  /** Server access log buckets are not logged to themselves nor versioned. */
  logBucketLogging: "S3_BUCKET_LOGGING_ENABLED",
  logBucketVersioning: "S3_BUCKET_VERSIONING_ENABLED",
  /** False positive: the rule requires the property to be absent even when it is `false`. */
  subnetPublicIp: "SUBNET_AUTO_ASSIGN_PUBLIC_IP_DISABLED",
  /** False positive: the rule requires a literal `Resource: "*"` in the TLS-only statement. */
  bucketTls: "S3_BUCKET_SSL_REQUESTS_ONLY",
} as const;

type GuardRule = (typeof GUARD_EXCEPTIONS)[keyof typeof GUARD_EXCEPTIONS];

export function suppressGuard(resource: CfnResource, ...rules: GuardRule[]): void {
  const current = (resource.getMetadata("guard") as { SuppressedRules?: string[] } | undefined)
    ?.SuppressedRules;
  const merged = [...new Set([...(current ?? []), ...rules])].sort();
  resource.addMetadata("guard", { SuppressedRules: merged });
}

function hasTlsOnlyStatement(stack: Stack, policy: s3.CfnBucketPolicy): boolean {
  const document = stack.resolve(policy.policyDocument) as {
    Statement?: { Effect?: string; Condition?: { Bool?: Record<string, unknown> } }[];
  };
  return (document.Statement ?? []).some(
    (s) => s.Effect === "Deny" && String(s.Condition?.Bool?.["aws:SecureTransport"]) === "false",
  );
}

/** Applies the suppressions that follow from resource properties, so new resources stay checked. */
export class GuardSuppressions implements IAspect {
  visit(node: IConstruct): void {
    if (node instanceof lambda.CfnFunction) {
      suppressGuard(node, GUARD_EXCEPTIONS.lambdaVpc);
    } else if (node instanceof ec2.CfnRoute && node.gatewayId !== undefined) {
      suppressGuard(node, GUARD_EXCEPTIONS.igwRoute);
    } else if (node instanceof ec2.CfnSubnet && node.mapPublicIpOnLaunch === false) {
      suppressGuard(node, GUARD_EXCEPTIONS.subnetPublicIp);
    } else if (node instanceof s3.CfnBucketPolicy && hasTlsOnlyStatement(Stack.of(node), node)) {
      suppressGuard(node, GUARD_EXCEPTIONS.bucketTls);
    } else if (
      node instanceof CfnResource &&
      node.cfnResourceType === "AWS::Lambda::Function"
    ) {
      // CDK singleton providers (custom resources) are plain CfnResources.
      suppressGuard(node, GUARD_EXCEPTIONS.lambdaVpc);
    } else if (
      node instanceof CfnResource &&
      node.cfnResourceType === "AWS::IAM::Role" &&
      node.node.path.includes("/Custom::")
    ) {
      suppressGuard(node, GUARD_EXCEPTIONS.cdkInlinePolicy);
    }
  }
}
