import { CfnResource, Stack, Token, Validations } from "aws-cdk-lib";
import { IConstruct } from "constructs";

export interface NagAcknowledgment {
  /** cdk-nag rule id, optionally granular, e.g. `AwsSolutions-IAM5[Resource::*]`. */
  id: string;
  /** Why the finding is accepted. Required: no silent exceptions (AGENTS.md). */
  reason: string;
}

/** Acknowledge cdk-nag findings on a construct and its children, next to the code they justify. */
export function acknowledge(scope: IConstruct, ...rules: NagAcknowledgment[]): void {
  Validations.of(scope).acknowledge(...rules.map((rule) => ({ ...rule, id: findingText(scope, rule.id) })));
}

/**
 * A finding id as cdk-nag writes it. Ids built from names and ARNs may carry deploy-time
 * values (a stack parameter, the account): cdk-nag prints a reference as `<LogicalId>` and an
 * attribute as `<LogicalId.Attribute>`, so the id written next to the code must say the same.
 */
function findingText(scope: IConstruct, id: string): string {
  if (!Token.isUnresolved(id)) return id;
  const render = (value: unknown): string => {
    if (typeof value === "string") return value;
    if (value !== null && typeof value === "object") {
      const node = value as Record<string, unknown>;
      if (typeof node.Ref === "string") return `<${node.Ref}>`;
      if (Array.isArray(node["Fn::GetAtt"])) return `<${(node["Fn::GetAtt"] as string[]).join(".")}>`;
      if (Array.isArray(node["Fn::Join"])) {
        const [separator, parts] = node["Fn::Join"] as [string, unknown[]];
        return parts.map(render).join(separator);
      }
    }
    throw new Error(`cdk-nag acknowledgment with a value it cannot name: ${JSON.stringify(value)}`);
  };
  return render(Stack.of(scope).resolve(id));
}

export const REASONS = {
  xray: "X-Ray PutTraceSegments/PutTelemetryRecords do not support resource-level permissions.",
  pythonRuntime:
    "Python 3.13 is the pinned platform runtime (AGENTS.md stack); upgrades follow the release process.",
  cdkGrant:
    "Generated by a CDK grant on a single resource (KMS key, bucket prefix or function versions).",
} as const;

/** Granular IAM5 id for a `<LogicalId.Arn><suffix>` wildcard produced by CDK grants. */
export function arnWildcardFinding(resource: CfnResource, suffix: string, attr = "Arn"): string {
  const logicalId = Stack.of(resource).resolve(Stack.of(resource).getLogicalId(resource)) as string;
  return `AwsSolutions-IAM5[Resource::<${logicalId}.${attr}>${suffix}]`;
}

export const KMS_GRANT_ACTIONS: NagAcknowledgment[] = [
  { id: "AwsSolutions-IAM5[Action::kms:GenerateDataKey*]", reason: REASONS.cdkGrant },
  { id: "AwsSolutions-IAM5[Action::kms:ReEncrypt*]", reason: REASONS.cdkGrant },
];
