/**
 * Generates src/ from openapi.json (exported by `python -m mango_api.openapi`):
 *
 *   types.gen.ts       TypeScript types          (@hey-api/openapi-ts)
 *   zod.gen.ts         zod schemas               (@hey-api/openapi-ts)
 *   operations.gen.ts  one entry per JSON route  (this script)
 *
 * `--check` generates into a temporary folder and fails when src/ differs: the committed client
 * must match the committed OpenAPI document. Run `mise run api-client` to regenerate both.
 */
import { mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { createClient } from '@hey-api/openapi-ts';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const input = join(root, 'openapi.json');
const METHODS = ['get', 'put', 'post', 'delete', 'patch'];

const pascal = (id) =>
  id
    .split('_')
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
const camel = (id) => pascal(id).replace(/^./, (first) => first.toLowerCase());

/** The 2xx response with a JSON schema, or null (e.g. the SSE stream of POST /chat). */
function jsonResponse(operation) {
  for (const [status, response] of Object.entries(operation.responses ?? {})) {
    if (!/^2\d\d$/.test(status)) continue;
    const schema = response.content?.['application/json']?.schema;
    if (schema && Object.keys(schema).length > 0) return Number(status);
  }
  return null;
}

function operationsSource(document, zodSource) {
  const exported = new Set(
    [...zodSource.matchAll(/^export const (z\w+)\b/gm)].map((match) => match[1]),
  );
  const need = (name) => {
    if (!exported.has(name)) throw new Error(`zod.gen.ts does not export ${name}`);
    return name;
  };
  const entries = [];
  const skipped = [];
  for (const [path, item] of Object.entries(document.paths).sort(([a], [b]) => a.localeCompare(b))) {
    for (const method of METHODS) {
      const operation = item[method];
      if (!operation) continue;
      const id = operation.operationId;
      if (!/^[a-z][a-z0-9_]*$/.test(id)) throw new Error(`unexpected operationId: ${id}`);
      const status = jsonResponse(operation);
      if (status === null) {
        skipped.push(`${method.toUpperCase()} ${path}`);
        continue;
      }
      const name = pascal(id);
      const parameters = operation.parameters ?? [];
      const has = (where) => parameters.some((parameter) => parameter.in === where);
      entries.push({
        key: camel(id),
        method: method.toUpperCase(),
        path,
        status,
        pathParams: has('path') ? need(`z${name}Path`) : null,
        query: has('query') ? need(`z${name}Query`) : null,
        body: operation.requestBody ? need(`z${name}Body`) : null,
        response: need(`z${name}Response`),
      });
    }
  }
  const keys = entries.map((entry) => entry.key);
  if (new Set(keys).size !== keys.length) throw new Error('duplicate operation names');
  entries.sort((a, b) => a.key.localeCompare(b.key));
  const imports = [
    ...new Set(
      entries.flatMap((entry) =>
        [entry.pathParams, entry.query, entry.body, entry.response].filter(Boolean),
      ),
    ),
  ].sort();
  const lines = [
    '// This file is auto-generated by scripts/generate.mjs from openapi.json. Do not edit.',
    '',
    'import {',
    ...imports.map((name) => `    ${name},`),
    "} from './zod.gen';",
    '',
    '/**',
    ' * Every route of mango-api that answers JSON: how to call it and the zod schemas of its path',
    ' * parameters, query, body and response. Paths are relative to the API base path.',
    ...(skipped.length > 0
      ? [' *', ` * Not listed (no JSON response schema): ${skipped.join(', ')}.`]
      : []),
    ' */',
    'export const operations = {',
    ...entries.flatMap((entry) => [
      `    ${entry.key}: {`,
      `        method: '${entry.method}',`,
      `        path: '${entry.path}',`,
      `        status: ${String(entry.status)},`,
      `        pathParams: ${entry.pathParams ?? 'null'},`,
      `        query: ${entry.query ?? 'null'},`,
      `        body: ${entry.body ?? 'null'},`,
      `        response: ${entry.response},`,
      '    },',
    ]),
    '} as const;',
    '',
    'export type OperationId = keyof typeof operations;',
    '',
  ];
  return lines.join('\n');
}

async function generate(outDir) {
  await createClient({
    input,
    output: { path: outDir, clean: true, entryFile: false },
    // Component schemas end in `Schema` and operation schemas in `Path`, `Query`, `Body` or
    // `Response`, so the two can never collide (e.g. the `MeResponse` model and the `me` route).
    plugins: ['@hey-api/typescript', { name: 'zod', definitions: 'z{{name}}Schema' }],
    logs: { level: 'silent' },
  });
  const document = JSON.parse(readFileSync(input, 'utf8'));
  const zodSource = readFileSync(join(outDir, 'zod.gen.ts'), 'utf8');
  writeFileSync(join(outDir, 'operations.gen.ts'), operationsSource(document, zodSource));
}

const files = (dir) => readdirSync(dir).sort();

if (process.argv.includes('--check')) {
  const temp = mkdtempSync(join(tmpdir(), 'mango-api-client-'));
  try {
    await generate(temp);
    const src = join(root, 'src');
    const stale =
      files(temp).join() !== files(src).join() ||
      files(temp).some(
        (file) => readFileSync(join(temp, file), 'utf8') !== readFileSync(join(src, file), 'utf8'),
      );
    if (stale) {
      console.error('packages/ts/api-client/src is out of date: run `mise run api-client`.');
      process.exitCode = 1;
    } else {
      console.log('api-client: src/ matches openapi.json');
    }
  } finally {
    rmSync(temp, { recursive: true, force: true });
  }
} else {
  await generate(join(root, 'src'));
}
