// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * ActionOut
 */
export type ActionOut = {
    /**
     * Change Id
     */
    change_id?: string | null;
    /**
     * Result
     */
    result: 'applied' | 'proposed' | 'bootstrap';
};

/**
 * AdminModelOut
 */
export type AdminModelOut = {
    /**
     * Agents
     */
    agents: Array<ModelAgentOut>;
    /**
     * Cache Read Usd
     */
    cache_read_usd: string | null;
    /**
     * Cache Write Usd
     */
    cache_write_usd: string | null;
    /**
     * Confirmed At
     */
    confirmed_at: string | null;
    /**
     * Confirmed By
     */
    confirmed_by: string | null;
    /**
     * Context Tokens
     */
    context_tokens: number | null;
    /**
     * Disabled At
     */
    disabled_at: string | null;
    /**
     * Disabled By
     */
    disabled_by: string | null;
    /**
     * Disabled Reason
     */
    disabled_reason: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Input Usd
     */
    input_usd: string | null;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * List Input Usd
     */
    list_input_usd: string | null;
    /**
     * List Output Usd
     */
    list_output_usd: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Output Usd
     */
    output_usd: string | null;
    /**
     * Provider
     */
    provider: string;
    /**
     * Status
     */
    status: 'enabled' | 'available' | 'disabled' | 'noaccess';
    /**
     * Supports Tools
     */
    supports_tools: boolean;
    /**
     * Supports Vision
     */
    supports_vision: boolean;
};

/**
 * AdminModelsOut
 */
export type AdminModelsOut = {
    /**
     * Items
     */
    items: Array<AdminModelOut>;
    /**
     * Refreshed At
     */
    refreshed_at: string | null;
    /**
     * Region
     */
    region: string;
    /**
     * Version
     */
    version: number;
};

/**
 * AgentBudgetOut
 */
export type AgentBudgetOut = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Limit Usd
     */
    limit_usd: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Spent Usd
     */
    spent_usd: string;
};

/**
 * AgentDefinition
 *
 * Content of one agent version. The agent's budget is not part of it (D22).
 */
export type AgentDefinition = {
    /**
     * Allowed Models
     */
    allowed_models?: Array<string>;
    /**
     * Approval Tools
     */
    approval_tools?: Array<string>;
    /**
     * Category
     */
    category?: string;
    /**
     * Color
     */
    color?: number;
    /**
     * Description
     */
    description?: string;
    /**
     * Groups
     */
    groups?: Array<string>;
    /**
     * Icon
     */
    icon?: string;
    limits?: AgentLimits;
    /**
     * Model
     */
    model?: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Reports To
     */
    reports_to?: string | null;
    /**
     * Role
     */
    role?: string;
    /**
     * System Prompt
     */
    system_prompt?: string;
    /**
     * Tools
     */
    tools?: Array<string>;
    /**
     * Users
     */
    users?: Array<string>;
};

/**
 * AgentLimits
 *
 * Harness limits per turn. Ranges follow the Agent Builder design.
 */
export type AgentLimits = {
    /**
     * Max Iterations
     */
    max_iterations?: number;
    /**
     * Max Tokens
     */
    max_tokens?: number;
    /**
     * Max Tokens Per Call
     */
    max_tokens_per_call?: number | null;
    /**
     * Temperature
     */
    temperature?: number | null;
    /**
     * Timeout Seconds
     */
    timeout_seconds?: number;
};

/**
 * AgentList
 */
export type AgentList = {
    /**
     * Items
     */
    items: Array<AgentOut>;
};

/**
 * AgentOut
 *
 * An agent as its users see it: no prompt and no access lists.
 */
export type AgentOut = {
    /**
     * Allowed Models
     */
    allowed_models: Array<string>;
    /**
     * Category
     */
    category: string;
    /**
     * Cleanup
     */
    cleanup?: 'running' | 'done' | 'failed' | null;
    /**
     * Color
     */
    color: number;
    /**
     * Description
     */
    description: string;
    /**
     * Icon
     */
    icon: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Mine
     */
    is_mine?: boolean;
    /**
     * Lock Version
     */
    lock_version: number | null;
    /**
     * Model
     */
    model: string;
    /**
     * Name
     */
    name: string;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Reports To
     */
    reports_to: string | null;
    /**
     * Retire Reason
     */
    retire_reason: string | null;
    /**
     * Retired At
     */
    retired_at: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Status
     */
    status: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * Unavailable Tools
     */
    unavailable_tools?: Array<string>;
    /**
     * Version
     */
    version: number;
};

/**
 * AgentStateOut
 */
export type AgentStateOut = {
    /**
     * Created By
     */
    created_by: string;
    /**
     * Lock Version
     */
    lock_version: number;
    /**
     * Open Version
     */
    open_version: number | null;
    /**
     * Published Version
     */
    published_version: number | null;
    /**
     * Status
     */
    status: string;
};

/**
 * ApprovalListOut
 */
export type ApprovalListOut = {
    /**
     * Can Decide
     */
    can_decide: boolean;
    /**
     * Items
     */
    items: Array<ApprovalOut>;
};

/**
 * ApprovalOut
 */
export type ApprovalOut = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Agent Name
     */
    agent_name: string | null;
    /**
     * Approval Id
     */
    approval_id: string;
    /**
     * Approvals Needed
     */
    approvals_needed: number;
    /**
     * Arguments
     */
    arguments: {
        [key: string]: unknown;
    };
    /**
     * Can Sign
     */
    can_sign: boolean;
    /**
     * Conversation Id
     */
    conversation_id: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    /**
     * Description
     */
    description: string;
    /**
     * Error
     */
    error: string | null;
    /**
     * Executed At
     */
    executed_at: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Mine
     */
    mine: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Requested By
     */
    requested_by: string;
    /**
     * Requested By Email
     */
    requested_by_email: string | null;
    rule: RuleOut;
    /**
     * Server Name
     */
    server_name: string;
    /**
     * Signatures
     */
    signatures: Array<SignatureOut>;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'executing' | 'executed' | 'failed' | 'rejected' | 'cancelled' | 'expired';
    /**
     * Tier
     */
    tier: 'self' | 'approvers';
    /**
     * Tool
     */
    tool: string;
};

/**
 * ApproveIn
 */
export type ApproveIn = {
    /**
     * Note
     */
    note?: string | null;
};

/**
 * AuditEventOut
 */
export type AuditEventOut = {
    /**
     * Actor Email
     */
    actor_email?: string | null;
    /**
     * Actor Is Admin
     */
    actor_is_admin?: boolean | null;
    /**
     * Actor Role
     */
    actor_role?: string | null;
    /**
     * Detail
     */
    detail: {
        [key: string]: unknown;
    };
    /**
     * Event
     */
    event: string;
    /**
     * Event Id
     */
    event_id: string;
    /**
     * Hash
     */
    hash: string;
    resource?: AuditResource | null;
    /**
     * Ts
     */
    ts: string;
    /**
     * User Id
     */
    user_id: string | null;
};

/**
 * AuditList
 */
export type AuditList = {
    /**
     * Items
     */
    items: Array<AuditEventOut>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
};

/**
 * AuditResource
 */
export type AuditResource = {
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
};

/**
 * BudgetDefaultsIn
 */
export type BudgetDefaultsIn = {
    /**
     * Agent Monthly Usd
     */
    agent_monthly_usd: number | string;
    /**
     * User Monthly Usd
     */
    user_monthly_usd: number | string;
    /**
     * Version
     */
    version: number;
};

/**
 * BudgetDefaultsOut
 */
export type BudgetDefaultsOut = {
    /**
     * Agent Monthly Usd
     */
    agent_monthly_usd: string;
    /**
     * User Monthly Usd
     */
    user_monthly_usd: string;
};

/**
 * BudgetsOut
 */
export type BudgetsOut = {
    /**
     * Agents
     */
    agents: Array<AgentBudgetOut>;
    defaults: BudgetDefaultsOut;
    /**
     * Period
     */
    period: string;
    /**
     * Users
     */
    users: Array<UserBudgetOut>;
    /**
     * Version
     */
    version: number;
};

/**
 * BusinessUnitsOut
 */
export type BusinessUnitsOut = {
    /**
     * Pending
     */
    pending: Array<MangoApiAdminChangeOut>;
    /**
     * Units
     */
    units: {
        [key: string]: Array<string>;
    };
    /**
     * Version
     */
    version: number;
};

/**
 * CatalogAgent
 */
export type CatalogAgent = {
    /**
     * Category
     */
    category: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * CatalogConnector
 */
export type CatalogConnector = {
    /**
     * Agents
     */
    agents?: Array<CatalogAgent>;
    /**
     * Data Tier
     */
    data_tier: string;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Identity Mode
     */
    identity_mode: string;
    /**
     * Kind
     */
    kind: string;
    /**
     * Name
     */
    name: string;
    pack?: PackOut | null;
    /**
     * Permissions
     */
    permissions: Array<string>;
    /**
     * Provider
     */
    provider: string;
    /**
     * Tools
     */
    tools: Array<CatalogTool>;
};

/**
 * CatalogOut
 */
export type CatalogOut = {
    /**
     * Items
     */
    items: Array<CatalogConnector>;
    /**
     * Max Enabled Packs
     */
    max_enabled_packs?: number;
};

/**
 * CatalogTool
 */
export type CatalogTool = {
    /**
     * Access
     */
    access: string;
    /**
     * Audience
     */
    audience: string;
    /**
     * Central Groups Only
     */
    central_groups_only: boolean;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Name
     */
    name: string;
    /**
     * Ref
     */
    ref: string;
    /**
     * Requires Service
     */
    requires_service?: string | null;
};

/**
 * ChangeCreatedOut
 */
export type ChangeCreatedOut = {
    /**
     * Change Id
     */
    change_id: string;
};

/**
 * ChangeKind
 */
export type ChangeKind = 'enable' | 'params' | 'update';

/**
 * ChangeListOut
 */
export type ChangeListOut = {
    /**
     * Items
     */
    items: Array<MangoApiPeopleChangeOut>;
};

/**
 * ChatRequest
 *
 * A turn. Besides the message the client only picks the agent of a new conversation and
 * one of that agent's allowed models; everything else comes from the published version.
 */
export type ChatRequest = {
    /**
     * Agent Id
     */
    agent_id?: string | null;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    /**
     * Message
     */
    message: string;
    /**
     * Model
     */
    model?: string | null;
};

/**
 * ConnectivityCheck
 */
export type ConnectivityCheck = {
    /**
     * Detail
     */
    detail: string;
    /**
     * Name
     */
    name: 'broker' | 'billing_reader' | 'organizations';
    /**
     * Status
     */
    status: 'ok' | 'error';
};

/**
 * ConnectivityOut
 */
export type ConnectivityOut = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Checks
     */
    checks: Array<ConnectivityCheck>;
};

/**
 * ConversationDetail
 */
export type ConversationDetail = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Approvals
     */
    approvals?: Array<ApprovalOut>;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Messages
     */
    messages: Array<MessageOut>;
    /**
     * Title
     */
    title: string;
};

/**
 * ConversationList
 */
export type ConversationList = {
    /**
     * Items
     */
    items: Array<ConversationSummary>;
};

/**
 * ConversationSummary
 */
export type ConversationSummary = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * CreateAgentIn
 */
export type CreateAgentIn = {
    definition: AgentDefinition;
};

/**
 * DefinitionOut
 */
export type DefinitionOut = {
    /**
     * Allowed Models
     */
    allowed_models: Array<string>;
    /**
     * Approval Tools
     */
    approval_tools: Array<string>;
    /**
     * Category
     */
    category: string;
    /**
     * Color
     */
    color: number;
    /**
     * Description
     */
    description: string;
    /**
     * Groups
     */
    groups: Array<string>;
    /**
     * Icon
     */
    icon: string;
    limits: LimitsOut;
    /**
     * Model
     */
    model: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Reports To
     */
    reports_to: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * System Prompt
     */
    system_prompt: string;
    /**
     * Tools
     */
    tools: Array<string>;
    /**
     * Users
     */
    users: Array<string>;
};

/**
 * DescriptionIn
 */
export type DescriptionIn = {
    /**
     * Description
     */
    description: string;
    /**
     * Version
     */
    version: number;
};

/**
 * DiffOut
 *
 * Changes of a version against the published one, computed here (never by the SPA).
 */
export type DiffOut = {
    /**
     * Changes
     */
    changes: number;
    /**
     * Fields
     */
    fields: Array<FieldChange>;
    /**
     * Is New
     */
    is_new: boolean;
    /**
     * Prompt
     */
    prompt: Array<PromptLine> | null;
    /**
     * Sets
     */
    sets: Array<SetChange>;
};

/**
 * DirectoryUserOut
 */
export type DirectoryUserOut = {
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
};

/**
 * DisableIn
 */
export type DisableIn = {
    /**
     * Reason
     */
    reason: string;
    /**
     * Version
     */
    version: number;
};

/**
 * EmptyIn
 */
export type EmptyIn = {
    [key: string]: never;
};

/**
 * EnableIn
 */
export type EnableIn = {
    /**
     * Config
     */
    config?: {
        [key: string]: unknown | string;
    };
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Version
     */
    version: number;
};

/**
 * ErrorBody
 */
export type ErrorBody = {
    error: ErrorDetail;
};

/**
 * ErrorDetail
 */
export type ErrorDetail = {
    /**
     * Code
     */
    code: string;
    /**
     * Message
     */
    message: string;
};

/**
 * FieldChange
 */
export type FieldChange = {
    /**
     * After
     */
    after: string | number | number | null;
    /**
     * Before
     */
    before: string | number | number | null;
    /**
     * Field
     */
    field: string;
};

/**
 * GroupAdminOut
 */
export type GroupAdminOut = {
    /**
     * Agents
     */
    agents: Array<GroupAgentOut>;
    /**
     * Area
     */
    area: string | null;
    /**
     * Description
     */
    description: string;
    /**
     * Fixed Type
     */
    fixed_type: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * System
     */
    system: boolean;
    /**
     * Type
     */
    type: 'central' | 'area' | 'general';
    /**
     * Version
     */
    version: number;
};

/**
 * GroupAgentOut
 */
export type GroupAgentOut = {
    /**
     * Account Data
     */
    account_data: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * GroupChangeOut
 */
export type GroupChangeOut = {
    after: GroupTargetOut | null;
    /**
     * Agents
     */
    agents: number;
    before: GroupShapeOut | null;
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Kind
     */
    kind: 'create' | 'update' | 'delete';
    /**
     * Note
     */
    note: string | null;
    /**
     * Proposed By
     */
    proposed_by: string;
    /**
     * Proposed By Email
     */
    proposed_by_email: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'rejected' | 'withdrawn' | 'expired';
};

/**
 * GroupIn
 */
export type GroupIn = {
    /**
     * Group
     */
    group: string;
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * GroupList
 */
export type GroupList = {
    /**
     * Items
     */
    items: Array<GroupOut>;
};

/**
 * GroupOut
 */
export type GroupOut = {
    /**
     * Area
     */
    area: string | null;
    /**
     * Description
     */
    description: string;
    /**
     * Id
     */
    id: string;
    /**
     * Type
     */
    type: string;
};

/**
 * GroupShapeOut
 */
export type GroupShapeOut = {
    /**
     * Area
     */
    area: string | null;
    /**
     * Type
     */
    type: 'central' | 'area' | 'general';
};

/**
 * GroupTargetOut
 */
export type GroupTargetOut = {
    /**
     * Area
     */
    area: string | null;
    /**
     * Description
     */
    description: string | null;
    /**
     * Type
     */
    type: 'central' | 'area' | 'general';
};

/**
 * GroupsAdminOut
 */
export type GroupsAdminOut = {
    /**
     * Changes
     */
    changes: Array<GroupChangeOut>;
    /**
     * Items
     */
    items: Array<GroupAdminOut>;
};

/**
 * HashIn
 */
export type HashIn = {
    /**
     * Content Hash
     */
    content_hash: string;
};

/**
 * InstallationOut
 *
 * What was given when Mango was installed. Read only: whoever runs AWS changes it.
 */
export type InstallationOut = {
    /**
     * Alerts Emails
     */
    alerts_emails: Array<string>;
    /**
     * First Admins
     */
    first_admins: Array<string>;
    /**
     * Management Account Id
     */
    management_account_id: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * Organization Id
     */
    organization_id: string | null;
    /**
     * Release
     */
    release: string | null;
    /**
     * Sign Up Domains
     */
    sign_up_domains: Array<string>;
    /**
     * Version
     */
    version: string | null;
};

/**
 * InviteIn
 */
export type InviteIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Groups
     */
    groups?: Array<string>;
};

/**
 * InvitedOut
 */
export type InvitedOut = {
    /**
     * Result
     */
    result: 'applied' | 'bootstrap';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * LimitsOut
 */
export type LimitsOut = {
    /**
     * Max Iterations
     */
    max_iterations: number;
    /**
     * Max Tokens
     */
    max_tokens: number;
    /**
     * Max Tokens Per Call
     */
    max_tokens_per_call: number | null;
    /**
     * Temperature
     */
    temperature: number | null;
    /**
     * Timeout Seconds
     */
    timeout_seconds: number;
};

/**
 * MeCan
 *
 * Hints for the SPA only; the API authorizes every request on its own.
 */
export type MeCan = {
    /**
     * Create Agent
     */
    create_agent: boolean;
};

/**
 * MeResponse
 */
export type MeResponse = {
    /**
     * Business Unit
     */
    business_unit: string | null;
    can: MeCan;
    /**
     * Email
     */
    email: string | null;
    /**
     * Groups
     */
    groups: Array<string>;
    /**
     * Is Admin
     */
    is_admin: boolean;
    /**
     * Name
     */
    name: string | null;
    /**
     * Role
     */
    role: string | null;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * MemberAccessOut
 */
export type MemberAccessOut = {
    /**
     * Accounts
     */
    accounts: Array<MemberAccountOut>;
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Identity Required
     */
    identity_required: boolean | null;
    /**
     * Total
     */
    total: number;
    /**
     * Truncated
     */
    truncated: boolean;
};

/**
 * MemberAccountOut
 */
export type MemberAccountOut = {
    /**
     * Account Id
     */
    account_id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'role_missing' | 'identity_not_required';
};

/**
 * MessageOut
 */
export type MessageOut = {
    /**
     * Approvals
     */
    approvals?: Array<string>;
    /**
     * Content
     */
    content: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Message Id
     */
    message_id: string;
    /**
     * Role
     */
    role: string;
    /**
     * Tools
     */
    tools: Array<ToolStatus>;
};

/**
 * MineOut
 */
export type MineOut = {
    /**
     * Items
     */
    items: Array<VersionSummary>;
    quotas: QuotasOut;
};

/**
 * ModelAgentOut
 */
export type ModelAgentOut = {
    /**
     * Category
     */
    category: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

/**
 * ModelOut
 */
export type ModelOut = {
    /**
     * Context Tokens
     */
    context_tokens: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Input Usd
     */
    input_usd: string;
    /**
     * Name
     */
    name: string;
    /**
     * Output Usd
     */
    output_usd: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Supports Tools
     */
    supports_tools: boolean;
};

/**
 * ModelUpdateIn
 *
 * Enable a model (or change the prices of an enabled one), or disable it.
 */
export type ModelUpdateIn = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Input Usd
     */
    input_usd?: number | string | null;
    /**
     * Output Usd
     */
    output_usd?: number | string | null;
    /**
     * Reason
     */
    reason?: string | null;
    /**
     * Version
     */
    version: number;
};

/**
 * ModelsOut
 */
export type ModelsOut = {
    /**
     * Items
     */
    items: Array<ModelOut>;
    /**
     * Version
     */
    version: number;
};

/**
 * OptionalReasonIn
 */
export type OptionalReasonIn = {
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * OrgNode
 */
export type OrgNode = {
    /**
     * Can Edit
     */
    can_edit: boolean;
    /**
     * Can Use
     */
    can_use: boolean;
    /**
     * Category
     */
    category: string;
    /**
     * Color
     */
    color: number;
    /**
     * Description
     */
    description: string;
    /**
     * Groups
     */
    groups: Array<string>;
    /**
     * Icon
     */
    icon: string;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Reports To
     */
    reports_to: string | null;
    /**
     * Role
     */
    role: string;
    /**
     * Version
     */
    version: number;
};

/**
 * OrgOut
 */
export type OrgOut = {
    /**
     * Nodes
     */
    nodes: Array<OrgNode>;
    /**
     * Root
     */
    root: string;
};

/**
 * OrganizationOut
 */
export type OrganizationOut = {
    /**
     * Ous
     */
    ous: Array<OrganizationalUnit>;
};

/**
 * OrganizationalUnit
 */
export type OrganizationalUnit = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Parent Id
     */
    parent_id: string;
    /**
     * Path
     */
    path: Array<string>;
};

/**
 * PackDecision
 */
export type PackDecision = {
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    kind: ChangeKind;
    /**
     * Reason
     */
    reason: string | null;
};

/**
 * PackOut
 */
export type PackOut = {
    /**
     * Approved At
     */
    approved_at?: string | null;
    /**
     * Approved By
     */
    approved_by?: string | null;
    /**
     * Approved By Email
     */
    approved_by_email?: string | null;
    /**
     * Disable Reason
     */
    disable_reason?: string | null;
    /**
     * Disabled At
     */
    disabled_at?: string | null;
    /**
     * Disabled By
     */
    disabled_by?: string | null;
    /**
     * Disabled By Email
     */
    disabled_by_email?: string | null;
    /**
     * Failed Step
     */
    failed_step?: string | null;
    /**
     * Failure
     */
    failure?: string | null;
    /**
     * Installed Version
     */
    installed_version: string | null;
    last_rejected?: PackDecision | null;
    /**
     * Lock Version
     */
    lock_version: number;
    /**
     * Params
     */
    params: Array<PackParam>;
    pending?: PackRequest | null;
    /**
     * Requested At
     */
    requested_at?: string | null;
    /**
     * Requested By
     */
    requested_by?: string | null;
    /**
     * Requested By Email
     */
    requested_by_email?: string | null;
    /**
     * Status
     */
    status: 'available' | 'pending' | 'installing' | 'enabled' | 'error' | 'disabling' | 'disabled';
    /**
     * Status At
     */
    status_at?: string | null;
    update: PackUpdate | null;
    /**
     * Version
     */
    version: string;
};

/**
 * PackParam
 */
export type PackParam = {
    /**
     * Allowed
     */
    allowed: Array<string>;
    /**
     * Default
     */
    default: string;
    /**
     * Description
     */
    description: string | null;
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string | null;
};

/**
 * PackRequest
 */
export type PackRequest = {
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Config
     */
    config: {
        [key: string]: string;
    };
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
    kind: ChangeKind;
    /**
     * Own
     */
    own: boolean;
    /**
     * Pack Version
     */
    pack_version: string;
    /**
     * Reason
     */
    reason: string | null;
    /**
     * Requested By
     */
    requested_by: string;
    /**
     * Requested By Email
     */
    requested_by_email: string | null;
};

/**
 * PackUpdate
 *
 * What moving from the installed version to the release's version changes.
 */
export type PackUpdate = {
    /**
     * Added Permissions
     */
    added_permissions: Array<string>;
    /**
     * Added Tools
     */
    added_tools: Array<string>;
    /**
     * Removed Permissions
     */
    removed_permissions: Array<string>;
    /**
     * Removed Tools
     */
    removed_tools: Array<string>;
    /**
     * Version
     */
    version: string;
};

/**
 * ParamsIn
 */
export type ParamsIn = {
    /**
     * Config
     */
    config: {
        [key: string]: unknown | string;
    };
    /**
     * Version
     */
    version: number;
};

/**
 * PeopleOut
 */
export type PeopleOut = {
    /**
     * Admins
     */
    admins: number;
    /**
     * Incomplete
     */
    incomplete: boolean;
    /**
     * Items
     */
    items: Array<PersonOut>;
    /**
     * Next Cursor
     */
    next_cursor: string | null;
    /**
     * Pending
     */
    pending: number;
    /**
     * With Access
     */
    with_access: number;
};

/**
 * PersonOut
 */
export type PersonOut = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Email
     */
    email: string;
    /**
     * Groups
     */
    groups: Array<string>;
    /**
     * Mfa
     */
    mfa: boolean;
    /**
     * Status
     */
    status: 'active' | 'invited' | 'disabled';
    /**
     * User Id
     */
    user_id: string;
};

/**
 * PoliciesOut
 */
export type PoliciesOut = {
    /**
     * Changes
     */
    changes: Array<PolicyChangeOut>;
    /**
     * Tools
     */
    tools: Array<ToolPolicyOut>;
};

/**
 * PolicyChangeOut
 */
export type PolicyChangeOut = {
    after: PolicyRule;
    before: PolicyRule;
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Note
     */
    note: string | null;
    /**
     * Proposed By
     */
    proposed_by: string;
    /**
     * Proposed By Email
     */
    proposed_by_email: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'rejected' | 'withdrawn' | 'expired';
    /**
     * Tool
     */
    tool: string;
};

/**
 * PolicyRule
 *
 * A policy as shown: only the threshold of its condition is set.
 */
export type PolicyRule = {
    /**
     * Amount Usd
     */
    amount_usd?: string | null;
    /**
     * Approvers
     */
    approvers: number;
    /**
     * Condition
     */
    condition: 'always' | 'amount' | 'count' | 'environment';
    /**
     * Count
     */
    count?: number | null;
    /**
     * Environment
     */
    environment?: 'prod' | 'staging' | null;
    /**
     * Expires Hours
     */
    expires_hours: 1 | 4 | 24 | 48 | 72;
};

/**
 * PromptLine
 */
export type PromptLine = {
    /**
     * Op
     */
    op: '+' | '-' | ' ';
    /**
     * Text
     */
    text: string;
};

/**
 * ProposalIn
 */
export type ProposalIn = {
    /**
     * Base Version
     */
    base_version: number;
    /**
     * Reason
     */
    reason: string;
    /**
     * Units
     */
    units: {
        [key: string]: unknown | Array<string>;
    };
};

/**
 * QuotasOut
 */
export type QuotasOut = {
    /**
     * Drafts
     */
    drafts: number;
    /**
     * Max Drafts
     */
    max_drafts: number;
    /**
     * Max Submissions Per Day
     */
    max_submissions_per_day: number;
    /**
     * Submissions Today
     */
    submissions_today: number;
};

/**
 * ReasonIn
 */
export type ReasonIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * RenewedOut
 */
export type RenewedOut = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Federated
     */
    federated: boolean;
    /**
     * Id Token
     */
    id_token: string;
};

/**
 * ResetCreatedOut
 */
export type ResetCreatedOut = {
    /**
     * Change Id
     */
    change_id: string;
};

/**
 * ResetListOut
 */
export type ResetListOut = {
    /**
     * Items
     */
    items: Array<ResetOut>;
};

/**
 * ResetOut
 */
export type ResetOut = {
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Identity Verified
     */
    identity_verified: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Proposed By
     */
    proposed_by: string;
    /**
     * Proposed By Email
     */
    proposed_by_email: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'rejected' | 'withdrawn' | 'expired';
    /**
     * Target Email
     */
    target_email: string | null;
    /**
     * Target User
     */
    target_user: string;
};

/**
 * ResolveIn
 */
export type ResolveIn = {
    /**
     * Emails
     */
    emails?: Array<string>;
    /**
     * Ids
     */
    ids?: Array<string>;
};

/**
 * ResolveOut
 */
export type ResolveOut = {
    /**
     * Emails Not Found
     */
    emails_not_found: Array<string>;
    /**
     * Ids Not Found
     */
    ids_not_found: Array<string>;
    /**
     * Users
     */
    users: Array<DirectoryUserOut>;
};

/**
 * RetireIn
 */
export type RetireIn = {
    /**
     * Lock Version
     */
    lock_version: number;
    /**
     * Reason
     */
    reason: string;
};

/**
 * RetryIn
 */
export type RetryIn = {
    /**
     * Version
     */
    version: number;
};

/**
 * ReviewOut
 */
export type ReviewOut = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Approved At
     */
    approved_at: string | null;
    /**
     * Approved By
     */
    approved_by: string | null;
    /**
     * Approved By Email
     */
    approved_by_email: string | null;
    /**
     * Category
     */
    category: string;
    /**
     * Changes
     */
    changes: number | null;
    /**
     * Color
     */
    color: number;
    /**
     * Content Hash
     */
    content_hash: string | null;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created By Email
     */
    created_by_email: string | null;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Description
     */
    description: string;
    /**
     * Failed Step
     */
    failed_step: string | null;
    /**
     * Icon
     */
    icon: string;
    /**
     * Is Author
     */
    is_author: boolean;
    /**
     * Kind
     */
    kind: 'new' | 'change';
    /**
     * Name
     */
    name: string;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Rejected At
     */
    rejected_at: string | null;
    /**
     * Rejected By
     */
    rejected_by: string | null;
    /**
     * Rejected By Email
     */
    rejected_by_email: string | null;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
    /**
     * Retire Reason
     */
    retire_reason: string | null;
    /**
     * Retired At
     */
    retired_at: string | null;
    /**
     * Retired By
     */
    retired_by: string | null;
    /**
     * Retired By Email
     */
    retired_by_email: string | null;
    /**
     * Retryable
     */
    retryable: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * Submitted At
     */
    submitted_at: string | null;
    /**
     * Version
     */
    version: number;
};

/**
 * ReviewsOut
 */
export type ReviewsOut = {
    /**
     * History
     */
    history: Array<ReviewOut>;
    /**
     * Queue
     */
    queue: Array<ReviewOut>;
};

/**
 * RuleOut
 *
 * The policy the request was born with and why it fell in its tier.
 */
export type RuleOut = {
    /**
     * Amount Usd
     */
    amount_usd?: string | null;
    /**
     * Approvers
     */
    approvers: number;
    /**
     * Condition
     */
    condition: 'always' | 'amount' | 'count' | 'environment';
    /**
     * Count
     */
    count?: number | null;
    /**
     * Environment
     */
    environment?: string | null;
    /**
     * Expires Hours
     */
    expires_hours: number;
    /**
     * Reason
     */
    reason: 'always' | 'above' | 'below' | 'unknown';
};

/**
 * SaveDraftIn
 */
export type SaveDraftIn = {
    definition: AgentDefinition;
    /**
     * Revision
     */
    revision: number;
};

/**
 * SearchIn
 */
export type SearchIn = {
    /**
     * Cursor
     */
    cursor?: string | null;
    /**
     * Filter
     */
    filter?: 'all' | 'pending' | 'invited' | 'disabled';
    /**
     * Prefix
     */
    prefix?: string | null;
};

/**
 * SessionIn
 */
export type SessionIn = {
    /**
     * Federated
     */
    federated?: boolean;
    /**
     * Refresh Token
     */
    refresh_token: string;
};

/**
 * SetChange
 */
export type SetChange = {
    /**
     * Added
     */
    added: Array<string>;
    /**
     * Field
     */
    field: string;
    /**
     * Removed
     */
    removed: Array<string>;
};

/**
 * SignatureOut
 */
export type SignatureOut = {
    /**
     * At
     */
    at: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Note
     */
    note: string | null;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * SubmitIn
 */
export type SubmitIn = {
    /**
     * Revision
     */
    revision: number;
};

/**
 * ToolPolicyOut
 */
export type ToolPolicyOut = {
    /**
     * Conditions
     */
    conditions: Array<'always' | 'amount' | 'count' | 'environment'>;
    /**
     * Description
     */
    description: string;
    /**
     * Pending Change Id
     */
    pending_change_id: string | null;
    policy: PolicyRule;
    /**
     * Server Name
     */
    server_name: string;
    /**
     * Tool
     */
    tool: string;
    /**
     * Version
     */
    version: number;
};

/**
 * ToolStatus
 */
export type ToolStatus = {
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: string;
};

/**
 * UpdateIn
 */
export type UpdateIn = {
    /**
     * Config
     */
    config?: {
        [key: string]: unknown | string;
    } | null;
    /**
     * Version
     */
    version: number;
};

/**
 * UserBudgetIn
 */
export type UserBudgetIn = {
    /**
     * Limit Usd
     */
    limit_usd: number | string | null;
    /**
     * Version
     */
    version: number;
};

/**
 * UserBudgetOut
 */
export type UserBudgetOut = {
    /**
     * Email
     */
    email: string | null;
    /**
     * Limit Usd
     */
    limit_usd: string;
    /**
     * Override
     */
    override: boolean;
    /**
     * Spent Usd
     */
    spent_usd: string;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * VersionOut
 */
export type VersionOut = {
    agent: AgentStateOut;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Approved At
     */
    approved_at: string | null;
    /**
     * Approved By
     */
    approved_by: string | null;
    /**
     * Approved By Email
     */
    approved_by_email: string | null;
    base: DefinitionOut | null;
    /**
     * Base Version
     */
    base_version: number | null;
    /**
     * Content Hash
     */
    content_hash: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string;
    /**
     * Created By Email
     */
    created_by_email: string | null;
    definition: DefinitionOut;
    diff: DiffOut;
    /**
     * Failed Step
     */
    failed_step: string | null;
    /**
     * Failure
     */
    failure: string | null;
    /**
     * Is Author
     */
    is_author: boolean;
    /**
     * Published At
     */
    published_at: string | null;
    /**
     * Rejected At
     */
    rejected_at: string | null;
    /**
     * Rejected By
     */
    rejected_by: string | null;
    /**
     * Rejected By Email
     */
    rejected_by_email: string | null;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
    /**
     * Revision
     */
    revision: number;
    /**
     * Status
     */
    status: string;
    /**
     * Submitted At
     */
    submitted_at: string | null;
    /**
     * Submitted By
     */
    submitted_by: string | null;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Version
     */
    version: number;
    /**
     * Violations
     */
    violations: Array<ViolationOut> | null;
};

/**
 * VersionSummary
 */
export type VersionSummary = {
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Base Version
     */
    base_version: number | null;
    /**
     * Category
     */
    category: string;
    /**
     * Color
     */
    color: number;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Description
     */
    description: string;
    /**
     * Failed Step
     */
    failed_step: string | null;
    /**
     * Icon
     */
    icon: string;
    /**
     * Name
     */
    name: string;
    /**
     * Rejected At
     */
    rejected_at: string | null;
    /**
     * Rejection Reason
     */
    rejection_reason: string | null;
    /**
     * Revision
     */
    revision: number;
    /**
     * Status
     */
    status: string;
    /**
     * Submitted At
     */
    submitted_at: string | null;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Version
     */
    version: number;
};

/**
 * ViolationOut
 */
export type ViolationOut = {
    /**
     * Code
     */
    code: string;
    /**
     * Field
     */
    field: string;
    /**
     * Items
     */
    items: Array<string>;
};

/**
 * ChangeOut
 */
export type MangoApiAdminChangeOut = {
    /**
     * Base Version
     */
    base_version: number;
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Proposed By
     */
    proposed_by: string;
    /**
     * Proposed By Email
     */
    proposed_by_email: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Units
     */
    units: {
        [key: string]: Array<string>;
    };
};

/**
 * RejectIn
 */
export type MangoApiAdminRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * RejectIn
 */
export type MangoApiAgentsRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * RejectIn
 */
export type MangoApiApprovalsRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * ProposeIn
 */
export type MangoApiGroupAdminProposeIn = {
    /**
     * Area
     */
    area?: string | null;
    /**
     * Base Version
     */
    base_version?: number | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Group Id
     */
    group_id: string;
    /**
     * Kind
     */
    kind: 'create' | 'update' | 'delete';
    /**
     * Reason
     */
    reason: string;
    /**
     * Type
     */
    type?: 'central' | 'area' | 'general' | null;
};

/**
 * RejectIn
 */
export type MangoApiGroupAdminRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * RejectIn
 */
export type MangoApiMcpRejectIn = {
    /**
     * Reason
     */
    reason?: string | null;
};

/**
 * ProposeIn
 */
export type MangoApiMfaResetProposeIn = {
    /**
     * Email
     */
    email: string;
    /**
     * Identity Verified
     */
    identity_verified: true;
    /**
     * Reason
     */
    reason: string;
};

/**
 * RejectIn
 */
export type MangoApiMfaResetRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

/**
 * ChangeOut
 */
export type MangoApiPeopleChangeOut = {
    /**
     * Change Id
     */
    change_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Decided At
     */
    decided_at: string | null;
    /**
     * Decided By
     */
    decided_by: string | null;
    /**
     * Decided By Email
     */
    decided_by_email: string | null;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Group
     */
    group: string | null;
    /**
     * Kind
     */
    kind: 'add' | 'remove' | 'disable' | 'enable';
    /**
     * Note
     */
    note: string | null;
    /**
     * Proposed By
     */
    proposed_by: string;
    /**
     * Proposed By Email
     */
    proposed_by_email: string | null;
    /**
     * Reason
     */
    reason: string;
    /**
     * Status
     */
    status: 'pending' | 'approved' | 'rejected' | 'withdrawn' | 'expired';
    /**
     * Target Email
     */
    target_email: string;
    /**
     * Target In Directory
     */
    target_in_directory: boolean | null;
    /**
     * Target User
     */
    target_user: string;
};

/**
 * ProposeIn
 */
export type MangoApiToolPoliciesProposeIn = {
    /**
     * Amount Usd
     */
    amount_usd?: string | null;
    /**
     * Approvers
     */
    approvers: number;
    /**
     * Base Version
     */
    base_version: number;
    /**
     * Condition
     */
    condition: 'always' | 'amount' | 'count' | 'environment';
    /**
     * Count
     */
    count?: number | null;
    /**
     * Environment
     */
    environment?: 'prod' | 'staging' | null;
    /**
     * Expires Hours
     */
    expires_hours: 1 | 4 | 24 | 48 | 72;
    /**
     * Reason
     */
    reason: string;
};

/**
 * RejectIn
 */
export type MangoApiToolPoliciesRejectIn = {
    /**
     * Reason
     */
    reason: string;
};

export type AdminAuditData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Cursor
         */
        cursor?: string | null;
        /**
         * Since
         */
        since?: string | null;
        /**
         * Until
         */
        until?: string | null;
        /**
         * Exclude
         */
        exclude?: Array<'reads'>;
        /**
         * Event
         */
        event?: string | null;
    };
    url: '/admin/audit';
};

export type AdminAuditErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type AdminAuditError = AdminAuditErrors[keyof AdminAuditErrors];

export type AdminAuditResponses = {
    /**
     * Successful Response
     */
    200: AuditList;
};

export type AdminAuditResponse = AdminAuditResponses[keyof AdminAuditResponses];

export type GetBudgetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/budgets';
};

export type GetBudgetsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetBudgetsError = GetBudgetsErrors[keyof GetBudgetsErrors];

export type GetBudgetsResponses = {
    /**
     * Successful Response
     */
    200: BudgetsOut;
};

export type GetBudgetsResponse = GetBudgetsResponses[keyof GetBudgetsResponses];

export type PutDefaultsData = {
    body: BudgetDefaultsIn;
    path?: never;
    query?: never;
    url: '/admin/budgets/defaults';
};

export type PutDefaultsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PutDefaultsError = PutDefaultsErrors[keyof PutDefaultsErrors];

export type PutDefaultsResponses = {
    /**
     * Successful Response
     */
    200: BudgetsOut;
};

export type PutDefaultsResponse = PutDefaultsResponses[keyof PutDefaultsResponses];

export type PutUserBudgetData = {
    body: UserBudgetIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/admin/budgets/users/{user_id}';
};

export type PutUserBudgetErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PutUserBudgetError = PutUserBudgetErrors[keyof PutUserBudgetErrors];

export type PutUserBudgetResponses = {
    /**
     * Successful Response
     */
    200: BudgetsOut;
};

export type PutUserBudgetResponse = PutUserBudgetResponses[keyof PutUserBudgetResponses];

export type GetBusinessUnitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/business-units';
};

export type GetBusinessUnitsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetBusinessUnitsError = GetBusinessUnitsErrors[keyof GetBusinessUnitsErrors];

export type GetBusinessUnitsResponses = {
    /**
     * Successful Response
     */
    200: BusinessUnitsOut;
};

export type GetBusinessUnitsResponse = GetBusinessUnitsResponses[keyof GetBusinessUnitsResponses];

export type PostChangeData = {
    body: ProposalIn;
    path?: never;
    query?: never;
    url: '/admin/business-units/changes';
};

export type PostChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PostChangeError = PostChangeErrors[keyof PostChangeErrors];

export type PostChangeResponses = {
    /**
     * Successful Response
     */
    201: ChangeCreatedOut;
};

export type PostChangeResponse = PostChangeResponses[keyof PostChangeResponses];

export type ApproveChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/business-units/changes/{change_id}/approve';
};

export type ApproveChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveChangeError = ApproveChangeErrors[keyof ApproveChangeErrors];

export type ApproveChangeResponses = {
    /**
     * Successful Response
     */
    200: BusinessUnitsOut;
};

export type ApproveChangeResponse = ApproveChangeResponses[keyof ApproveChangeResponses];

export type RejectChangeData = {
    body: MangoApiAdminRejectIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/business-units/changes/{change_id}/reject';
};

export type RejectChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectChangeError = RejectChangeErrors[keyof RejectChangeErrors];

export type RejectChangeResponses = {
    /**
     * Successful Response
     */
    200: BusinessUnitsOut;
};

export type RejectChangeResponse = RejectChangeResponses[keyof RejectChangeResponses];

export type WithdrawChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/business-units/changes/{change_id}/withdraw';
};

export type WithdrawChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawChangeError = WithdrawChangeErrors[keyof WithdrawChangeErrors];

export type WithdrawChangeResponses = {
    /**
     * Successful Response
     */
    200: BusinessUnitsOut;
};

export type WithdrawChangeResponse = WithdrawChangeResponses[keyof WithdrawChangeResponses];

export type ConnectivityCheckData = {
    body: EmptyIn;
    path?: never;
    query?: never;
    url: '/admin/connectivity-check';
};

export type ConnectivityCheckErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ConnectivityCheckError = ConnectivityCheckErrors[keyof ConnectivityCheckErrors];

export type ConnectivityCheckResponses = {
    /**
     * Successful Response
     */
    200: ConnectivityOut;
};

export type ConnectivityCheckResponse = ConnectivityCheckResponses[keyof ConnectivityCheckResponses];

export type GetAdminGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/groups';
};

export type GetAdminGroupsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetAdminGroupsError = GetAdminGroupsErrors[keyof GetAdminGroupsErrors];

export type GetAdminGroupsResponses = {
    /**
     * Successful Response
     */
    200: GroupsAdminOut;
};

export type GetAdminGroupsResponse = GetAdminGroupsResponses[keyof GetAdminGroupsResponses];

export type PostGroupChangeData = {
    body: MangoApiGroupAdminProposeIn;
    path?: never;
    query?: never;
    url: '/admin/groups/changes';
};

export type PostGroupChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PostGroupChangeError = PostGroupChangeErrors[keyof PostGroupChangeErrors];

export type PostGroupChangeResponses = {
    /**
     * Successful Response
     */
    201: ChangeCreatedOut;
};

export type PostGroupChangeResponse = PostGroupChangeResponses[keyof PostGroupChangeResponses];

export type ApproveGroupChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/groups/changes/{change_id}/approve';
};

export type ApproveGroupChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveGroupChangeError = ApproveGroupChangeErrors[keyof ApproveGroupChangeErrors];

export type ApproveGroupChangeResponses = {
    /**
     * Successful Response
     */
    200: GroupsAdminOut;
};

export type ApproveGroupChangeResponse = ApproveGroupChangeResponses[keyof ApproveGroupChangeResponses];

export type RejectGroupChangeData = {
    body: MangoApiGroupAdminRejectIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/groups/changes/{change_id}/reject';
};

export type RejectGroupChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectGroupChangeError = RejectGroupChangeErrors[keyof RejectGroupChangeErrors];

export type RejectGroupChangeResponses = {
    /**
     * Successful Response
     */
    200: GroupsAdminOut;
};

export type RejectGroupChangeResponse = RejectGroupChangeResponses[keyof RejectGroupChangeResponses];

export type WithdrawGroupChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/groups/changes/{change_id}/withdraw';
};

export type WithdrawGroupChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawGroupChangeError = WithdrawGroupChangeErrors[keyof WithdrawGroupChangeErrors];

export type WithdrawGroupChangeResponses = {
    /**
     * Successful Response
     */
    200: GroupsAdminOut;
};

export type WithdrawGroupChangeResponse = WithdrawGroupChangeResponses[keyof WithdrawGroupChangeResponses];

export type PutGroupDescriptionData = {
    body: DescriptionIn;
    path: {
        /**
         * Group Id
         */
        group_id: string;
    };
    query?: never;
    url: '/admin/groups/{group_id}/description';
};

export type PutGroupDescriptionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PutGroupDescriptionError = PutGroupDescriptionErrors[keyof PutGroupDescriptionErrors];

export type PutGroupDescriptionResponses = {
    /**
     * Successful Response
     */
    200: GroupsAdminOut;
};

export type PutGroupDescriptionResponse = PutGroupDescriptionResponses[keyof PutGroupDescriptionResponses];

export type GetInstallationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/installation';
};

export type GetInstallationErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetInstallationError = GetInstallationErrors[keyof GetInstallationErrors];

export type GetInstallationResponses = {
    /**
     * Successful Response
     */
    200: InstallationOut;
};

export type GetInstallationResponse = GetInstallationResponses[keyof GetInstallationResponses];

export type MemberAccessCheckData = {
    body: EmptyIn;
    path?: never;
    query?: never;
    url: '/admin/member-access-check';
};

export type MemberAccessCheckErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type MemberAccessCheckError = MemberAccessCheckErrors[keyof MemberAccessCheckErrors];

export type MemberAccessCheckResponses = {
    /**
     * Successful Response
     */
    200: MemberAccessOut;
};

export type MemberAccessCheckResponse = MemberAccessCheckResponses[keyof MemberAccessCheckResponses];

export type GetRequestsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/mfa-resets';
};

export type GetRequestsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetRequestsError = GetRequestsErrors[keyof GetRequestsErrors];

export type GetRequestsResponses = {
    /**
     * Successful Response
     */
    200: ResetListOut;
};

export type GetRequestsResponse = GetRequestsResponses[keyof GetRequestsResponses];

export type PostRequestData = {
    body: MangoApiMfaResetProposeIn;
    path?: never;
    query?: never;
    url: '/admin/mfa-resets';
};

export type PostRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PostRequestError = PostRequestErrors[keyof PostRequestErrors];

export type PostRequestResponses = {
    /**
     * Successful Response
     */
    201: ResetCreatedOut;
};

export type PostRequestResponse = PostRequestResponses[keyof PostRequestResponses];

export type ApproveRequestData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/mfa-resets/{change_id}/approve';
};

export type ApproveRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveRequestError = ApproveRequestErrors[keyof ApproveRequestErrors];

export type ApproveRequestResponses = {
    /**
     * Successful Response
     */
    200: ResetListOut;
};

export type ApproveRequestResponse = ApproveRequestResponses[keyof ApproveRequestResponses];

export type RejectRequestData = {
    body: MangoApiMfaResetRejectIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/mfa-resets/{change_id}/reject';
};

export type RejectRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectRequestError = RejectRequestErrors[keyof RejectRequestErrors];

export type RejectRequestResponses = {
    /**
     * Successful Response
     */
    200: ResetListOut;
};

export type RejectRequestResponse = RejectRequestResponses[keyof RejectRequestResponses];

export type WithdrawRequestData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/mfa-resets/{change_id}/withdraw';
};

export type WithdrawRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawRequestError = WithdrawRequestErrors[keyof WithdrawRequestErrors];

export type WithdrawRequestResponses = {
    /**
     * Successful Response
     */
    200: ResetListOut;
};

export type WithdrawRequestResponse = WithdrawRequestResponses[keyof WithdrawRequestResponses];

export type GetAdminModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/models';
};

export type GetAdminModelsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetAdminModelsError = GetAdminModelsErrors[keyof GetAdminModelsErrors];

export type GetAdminModelsResponses = {
    /**
     * Successful Response
     */
    200: AdminModelsOut;
};

export type GetAdminModelsResponse = GetAdminModelsResponses[keyof GetAdminModelsResponses];

export type RefreshAdminModelsData = {
    body: EmptyIn;
    path?: never;
    query?: never;
    url: '/admin/models/refresh';
};

export type RefreshAdminModelsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RefreshAdminModelsError = RefreshAdminModelsErrors[keyof RefreshAdminModelsErrors];

export type RefreshAdminModelsResponses = {
    /**
     * Successful Response
     */
    200: AdminModelsOut;
};

export type RefreshAdminModelsResponse = RefreshAdminModelsResponses[keyof RefreshAdminModelsResponses];

export type PutAdminModelData = {
    body: ModelUpdateIn;
    path: {
        /**
         * Model Id
         */
        model_id: string;
    };
    query?: never;
    url: '/admin/models/{model_id}';
};

export type PutAdminModelErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PutAdminModelError = PutAdminModelErrors[keyof PutAdminModelErrors];

export type PutAdminModelResponses = {
    /**
     * Successful Response
     */
    200: AdminModelsOut;
};

export type PutAdminModelResponse = PutAdminModelResponses[keyof PutAdminModelResponses];

export type GetOrganizationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/organization';
};

export type GetOrganizationErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetOrganizationError = GetOrganizationErrors[keyof GetOrganizationErrors];

export type GetOrganizationResponses = {
    /**
     * Successful Response
     */
    200: OrganizationOut;
};

export type GetOrganizationResponse = GetOrganizationResponses[keyof GetOrganizationResponses];

export type GetMemberChangesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/admin/people/changes';
};

export type GetMemberChangesErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetMemberChangesError = GetMemberChangesErrors[keyof GetMemberChangesErrors];

export type GetMemberChangesResponses = {
    /**
     * Successful Response
     */
    200: ChangeListOut;
};

export type GetMemberChangesResponse = GetMemberChangesResponses[keyof GetMemberChangesResponses];

export type ApproveMemberChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/people/changes/{change_id}/approve';
};

export type ApproveMemberChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveMemberChangeError = ApproveMemberChangeErrors[keyof ApproveMemberChangeErrors];

export type ApproveMemberChangeResponses = {
    /**
     * Successful Response
     */
    200: ChangeListOut;
};

export type ApproveMemberChangeResponse = ApproveMemberChangeResponses[keyof ApproveMemberChangeResponses];

export type RejectMemberChangeData = {
    body: ReasonIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/people/changes/{change_id}/reject';
};

export type RejectMemberChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectMemberChangeError = RejectMemberChangeErrors[keyof RejectMemberChangeErrors];

export type RejectMemberChangeResponses = {
    /**
     * Successful Response
     */
    200: ChangeListOut;
};

export type RejectMemberChangeResponse = RejectMemberChangeResponses[keyof RejectMemberChangeResponses];

export type WithdrawMemberChangeData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/admin/people/changes/{change_id}/withdraw';
};

export type WithdrawMemberChangeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawMemberChangeError = WithdrawMemberChangeErrors[keyof WithdrawMemberChangeErrors];

export type WithdrawMemberChangeResponses = {
    /**
     * Successful Response
     */
    200: ChangeListOut;
};

export type WithdrawMemberChangeResponse = WithdrawMemberChangeResponses[keyof WithdrawMemberChangeResponses];

export type InvitePersonData = {
    body: InviteIn;
    path?: never;
    query?: never;
    url: '/admin/people/invitations';
};

export type InvitePersonErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type InvitePersonError = InvitePersonErrors[keyof InvitePersonErrors];

export type InvitePersonResponses = {
    /**
     * Successful Response
     */
    201: InvitedOut;
};

export type InvitePersonResponse = InvitePersonResponses[keyof InvitePersonResponses];

export type SearchPeopleData = {
    body: SearchIn;
    path?: never;
    query?: never;
    url: '/admin/people/search';
};

export type SearchPeopleErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type SearchPeopleError = SearchPeopleErrors[keyof SearchPeopleErrors];

export type SearchPeopleResponses = {
    /**
     * Successful Response
     */
    200: PeopleOut;
};

export type SearchPeopleResponse = SearchPeopleResponses[keyof SearchPeopleResponses];

export type DisablePersonData = {
    body: ReasonIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/admin/people/{user_id}/disable';
};

export type DisablePersonErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type DisablePersonError = DisablePersonErrors[keyof DisablePersonErrors];

export type DisablePersonResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type DisablePersonResponse = DisablePersonResponses[keyof DisablePersonResponses];

export type EnablePersonData = {
    body: OptionalReasonIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/admin/people/{user_id}/enable';
};

export type EnablePersonErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type EnablePersonError = EnablePersonErrors[keyof EnablePersonErrors];

export type EnablePersonResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type EnablePersonResponse = EnablePersonResponses[keyof EnablePersonResponses];

export type AddGroupData = {
    body: GroupIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/admin/people/{user_id}/groups';
};

export type AddGroupErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type AddGroupError = AddGroupErrors[keyof AddGroupErrors];

export type AddGroupResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type AddGroupResponse = AddGroupResponses[keyof AddGroupResponses];

export type RemoveGroupData = {
    body: GroupIn;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/admin/people/{user_id}/groups/remove';
};

export type RemoveGroupErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RemoveGroupError = RemoveGroupErrors[keyof RemoveGroupErrors];

export type RemoveGroupResponses = {
    /**
     * Successful Response
     */
    200: ActionOut;
};

export type RemoveGroupResponse = RemoveGroupResponses[keyof RemoveGroupResponses];

export type GetAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents';
};

export type GetAgentsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetAgentsError = GetAgentsErrors[keyof GetAgentsErrors];

export type GetAgentsResponses = {
    /**
     * Successful Response
     */
    200: AgentList;
};

export type GetAgentsResponse = GetAgentsResponses[keyof GetAgentsResponses];

export type PostAgentData = {
    body: CreateAgentIn;
    path?: never;
    query?: never;
    url: '/agents';
};

export type PostAgentErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PostAgentError = PostAgentErrors[keyof PostAgentErrors];

export type PostAgentResponses = {
    /**
     * Successful Response
     */
    201: VersionOut;
};

export type PostAgentResponse = PostAgentResponses[keyof PostAgentResponses];

export type GetMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/mine';
};

export type GetMineErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetMineError = GetMineErrors[keyof GetMineErrors];

export type GetMineResponses = {
    /**
     * Successful Response
     */
    200: MineOut;
};

export type GetMineResponse = GetMineResponses[keyof GetMineResponses];

export type GetOrgData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/org';
};

export type GetOrgErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetOrgError = GetOrgErrors[keyof GetOrgErrors];

export type GetOrgResponses = {
    /**
     * Successful Response
     */
    200: OrgOut;
};

export type GetOrgResponse = GetOrgResponses[keyof GetOrgResponses];

export type GetReviewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/agents/reviews';
};

export type GetReviewsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetReviewsError = GetReviewsErrors[keyof GetReviewsErrors];

export type GetReviewsResponses = {
    /**
     * Successful Response
     */
    200: ReviewsOut;
};

export type GetReviewsResponse = GetReviewsResponses[keyof GetReviewsResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}';
};

export type GetAgentErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentOut;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type RetireAgentData = {
    body: RetireIn;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/retire';
};

export type RetireAgentErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RetireAgentError = RetireAgentErrors[keyof RetireAgentErrors];

export type RetireAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentOut;
};

export type RetireAgentResponse = RetireAgentResponses[keyof RetireAgentResponses];

export type PostVersionData = {
    body: EmptyIn;
    path: {
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions';
};

export type PostVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PostVersionError = PostVersionErrors[keyof PostVersionErrors];

export type PostVersionResponses = {
    /**
     * Successful Response
     */
    201: VersionOut;
};

export type PostVersionResponse = PostVersionResponses[keyof PostVersionResponses];

export type DeleteVersionData = {
    body?: never;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query: {
        /**
         * Revision
         */
        revision: number;
    };
    url: '/agents/{agent_id}/versions/{version}';
};

export type DeleteVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type DeleteVersionError = DeleteVersionErrors[keyof DeleteVersionErrors];

export type DeleteVersionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteVersionResponse = DeleteVersionResponses[keyof DeleteVersionResponses];

export type ReadVersionData = {
    body?: never;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}';
};

export type ReadVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ReadVersionError = ReadVersionErrors[keyof ReadVersionErrors];

export type ReadVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type ReadVersionResponse = ReadVersionResponses[keyof ReadVersionResponses];

export type PutVersionData = {
    body: SaveDraftIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}';
};

export type PutVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type PutVersionError = PutVersionErrors[keyof PutVersionErrors];

export type PutVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type PutVersionResponse = PutVersionResponses[keyof PutVersionResponses];

export type ApproveVersionData = {
    body: HashIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}/approve';
};

export type ApproveVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveVersionError = ApproveVersionErrors[keyof ApproveVersionErrors];

export type ApproveVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type ApproveVersionResponse = ApproveVersionResponses[keyof ApproveVersionResponses];

export type RejectVersionData = {
    body: MangoApiAgentsRejectIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}/reject';
};

export type RejectVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectVersionError = RejectVersionErrors[keyof RejectVersionErrors];

export type RejectVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type RejectVersionResponse = RejectVersionResponses[keyof RejectVersionResponses];

export type ReopenVersionData = {
    body: EmptyIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}/reopen';
};

export type ReopenVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ReopenVersionError = ReopenVersionErrors[keyof ReopenVersionErrors];

export type ReopenVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type ReopenVersionResponse = ReopenVersionResponses[keyof ReopenVersionResponses];

export type RetryVersionData = {
    body: HashIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}/retry';
};

export type RetryVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RetryVersionError = RetryVersionErrors[keyof RetryVersionErrors];

export type RetryVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type RetryVersionResponse = RetryVersionResponses[keyof RetryVersionResponses];

export type SubmitVersionData = {
    body: SubmitIn;
    path: {
        /**
         * Version
         */
        version: number;
        /**
         * Agent Id
         */
        agent_id: string;
    };
    query?: never;
    url: '/agents/{agent_id}/versions/{version}/submit';
};

export type SubmitVersionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type SubmitVersionError = SubmitVersionErrors[keyof SubmitVersionErrors];

export type SubmitVersionResponses = {
    /**
     * Successful Response
     */
    200: VersionOut;
};

export type SubmitVersionResponse = SubmitVersionResponses[keyof SubmitVersionResponses];

export type ListApprovalsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * View
         */
        view?: 'pending' | 'resolved';
        /**
         * Conversation Id
         */
        conversation_id?: string | null;
    };
    url: '/approvals';
};

export type ListApprovalsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ListApprovalsError = ListApprovalsErrors[keyof ListApprovalsErrors];

export type ListApprovalsResponses = {
    /**
     * Successful Response
     */
    200: ApprovalListOut;
};

export type ListApprovalsResponse = ListApprovalsResponses[keyof ListApprovalsResponses];

export type GetToolPoliciesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/approvals/policies';
};

export type GetToolPoliciesErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetToolPoliciesError = GetToolPoliciesErrors[keyof GetToolPoliciesErrors];

export type GetToolPoliciesResponses = {
    /**
     * Successful Response
     */
    200: PoliciesOut;
};

export type GetToolPoliciesResponse = GetToolPoliciesResponses[keyof GetToolPoliciesResponses];

export type ApproveToolPolicyData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/approvals/policies/changes/{change_id}/approve';
};

export type ApproveToolPolicyErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveToolPolicyError = ApproveToolPolicyErrors[keyof ApproveToolPolicyErrors];

export type ApproveToolPolicyResponses = {
    /**
     * Successful Response
     */
    200: PoliciesOut;
};

export type ApproveToolPolicyResponse = ApproveToolPolicyResponses[keyof ApproveToolPolicyResponses];

export type RejectToolPolicyData = {
    body: MangoApiToolPoliciesRejectIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/approvals/policies/changes/{change_id}/reject';
};

export type RejectToolPolicyErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectToolPolicyError = RejectToolPolicyErrors[keyof RejectToolPolicyErrors];

export type RejectToolPolicyResponses = {
    /**
     * Successful Response
     */
    200: PoliciesOut;
};

export type RejectToolPolicyResponse = RejectToolPolicyResponses[keyof RejectToolPolicyResponses];

export type WithdrawToolPolicyData = {
    body: EmptyIn;
    path: {
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/approvals/policies/changes/{change_id}/withdraw';
};

export type WithdrawToolPolicyErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawToolPolicyError = WithdrawToolPolicyErrors[keyof WithdrawToolPolicyErrors];

export type WithdrawToolPolicyResponses = {
    /**
     * Successful Response
     */
    200: PoliciesOut;
};

export type WithdrawToolPolicyResponse = WithdrawToolPolicyResponses[keyof WithdrawToolPolicyResponses];

export type ProposeToolPolicyData = {
    body: MangoApiToolPoliciesProposeIn;
    path: {
        /**
         * Tool
         */
        tool: string;
    };
    query?: never;
    url: '/approvals/policies/{tool}/changes';
};

export type ProposeToolPolicyErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ProposeToolPolicyError = ProposeToolPolicyErrors[keyof ProposeToolPolicyErrors];

export type ProposeToolPolicyResponses = {
    /**
     * Successful Response
     */
    201: ChangeCreatedOut;
};

export type ProposeToolPolicyResponse = ProposeToolPolicyResponses[keyof ProposeToolPolicyResponses];

export type GetApprovalData = {
    body?: never;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}';
};

export type GetApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetApprovalError = GetApprovalErrors[keyof GetApprovalErrors];

export type GetApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type GetApprovalResponse = GetApprovalResponses[keyof GetApprovalResponses];

export type ApproveApprovalData = {
    body: ApproveIn;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/approve';
};

export type ApproveApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApproveApprovalError = ApproveApprovalErrors[keyof ApproveApprovalErrors];

export type ApproveApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type ApproveApprovalResponse = ApproveApprovalResponses[keyof ApproveApprovalResponses];

export type CancelApprovalData = {
    body: EmptyIn;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/cancel';
};

export type CancelApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type CancelApprovalError = CancelApprovalErrors[keyof CancelApprovalErrors];

export type CancelApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type CancelApprovalResponse = CancelApprovalResponses[keyof CancelApprovalResponses];

export type ConfirmApprovalData = {
    body: EmptyIn;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/confirm';
};

export type ConfirmApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ConfirmApprovalError = ConfirmApprovalErrors[keyof ConfirmApprovalErrors];

export type ConfirmApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type ConfirmApprovalResponse = ConfirmApprovalResponses[keyof ConfirmApprovalResponses];

export type ExecuteApprovalData = {
    body: EmptyIn;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/execute';
};

export type ExecuteApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ExecuteApprovalError = ExecuteApprovalErrors[keyof ExecuteApprovalErrors];

export type ExecuteApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type ExecuteApprovalResponse = ExecuteApprovalResponses[keyof ExecuteApprovalResponses];

export type RejectApprovalData = {
    body: MangoApiApprovalsRejectIn;
    path: {
        /**
         * Approval Id
         */
        approval_id: string;
    };
    query?: never;
    url: '/approvals/{approval_id}/reject';
};

export type RejectApprovalErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectApprovalError = RejectApprovalErrors[keyof RejectApprovalErrors];

export type RejectApprovalResponses = {
    /**
     * Successful Response
     */
    200: ApprovalOut;
};

export type RejectApprovalResponse = RejectApprovalResponses[keyof RejectApprovalResponses];

export type ChatData = {
    body: ChatRequest;
    path?: never;
    query?: never;
    url: '/chat';
};

export type ChatErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ChatError = ChatErrors[keyof ChatErrors];

export type ChatResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListConversationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/conversations';
};

export type ListConversationsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ListConversationsError = ListConversationsErrors[keyof ListConversationsErrors];

export type ListConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationList;
};

export type ListConversationsResponse = ListConversationsResponses[keyof ListConversationsResponses];

export type GetConversationData = {
    body?: never;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/conversations/{conversation_id}';
};

export type GetConversationErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetConversationError = GetConversationErrors[keyof GetConversationErrors];

export type GetConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationDetail;
};

export type GetConversationResponse = GetConversationResponses[keyof GetConversationResponses];

export type ResolveUsersData = {
    body: ResolveIn;
    path?: never;
    query?: never;
    url: '/directory/users/resolve';
};

export type ResolveUsersErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ResolveUsersError = ResolveUsersErrors[keyof ResolveUsersErrors];

export type ResolveUsersResponses = {
    /**
     * Successful Response
     */
    200: ResolveOut;
};

export type ResolveUsersResponse = ResolveUsersResponses[keyof ResolveUsersResponses];

export type ListGroupsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/groups';
};

export type ListGroupsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ListGroupsError = ListGroupsErrors[keyof ListGroupsErrors];

export type ListGroupsResponses = {
    /**
     * Successful Response
     */
    200: GroupList;
};

export type ListGroupsResponse = ListGroupsResponses[keyof ListGroupsResponses];

export type HealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type HealthError = HealthErrors[keyof HealthErrors];

export type HealthResponses = {
    /**
     * Response Health Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthResponse = HealthResponses[keyof HealthResponses];

export type GetCatalogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/mcp/catalog';
};

export type GetCatalogErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetCatalogError = GetCatalogErrors[keyof GetCatalogErrors];

export type GetCatalogResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type GetCatalogResponse = GetCatalogResponses[keyof GetCatalogResponses];

export type DisablePackData = {
    body: DisableIn;
    path: {
        /**
         * Pack
         */
        pack: string;
    };
    query?: never;
    url: '/mcp/{pack}';
};

export type DisablePackErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type DisablePackError = DisablePackErrors[keyof DisablePackErrors];

export type DisablePackResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type DisablePackResponse = DisablePackResponses[keyof DisablePackResponses];

export type RequestPackEnablementData = {
    body: EnableIn;
    path: {
        /**
         * Pack
         */
        pack: string;
    };
    query?: never;
    url: '/mcp/{pack}/enablements';
};

export type RequestPackEnablementErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RequestPackEnablementError = RequestPackEnablementErrors[keyof RequestPackEnablementErrors];

export type RequestPackEnablementResponses = {
    /**
     * Successful Response
     */
    201: CatalogOut;
};

export type RequestPackEnablementResponse = RequestPackEnablementResponses[keyof RequestPackEnablementResponses];

export type ApprovePackRequestData = {
    body: EmptyIn;
    path: {
        /**
         * Pack
         */
        pack: string;
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/mcp/{pack}/enablements/{change_id}/approve';
};

export type ApprovePackRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type ApprovePackRequestError = ApprovePackRequestErrors[keyof ApprovePackRequestErrors];

export type ApprovePackRequestResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type ApprovePackRequestResponse = ApprovePackRequestResponses[keyof ApprovePackRequestResponses];

export type RejectPackRequestData = {
    body: MangoApiMcpRejectIn;
    path: {
        /**
         * Pack
         */
        pack: string;
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/mcp/{pack}/enablements/{change_id}/reject';
};

export type RejectPackRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RejectPackRequestError = RejectPackRequestErrors[keyof RejectPackRequestErrors];

export type RejectPackRequestResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type RejectPackRequestResponse = RejectPackRequestResponses[keyof RejectPackRequestResponses];

export type WithdrawPackRequestData = {
    body: EmptyIn;
    path: {
        /**
         * Pack
         */
        pack: string;
        /**
         * Change Id
         */
        change_id: string;
    };
    query?: never;
    url: '/mcp/{pack}/enablements/{change_id}/withdraw';
};

export type WithdrawPackRequestErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type WithdrawPackRequestError = WithdrawPackRequestErrors[keyof WithdrawPackRequestErrors];

export type WithdrawPackRequestResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type WithdrawPackRequestResponse = WithdrawPackRequestResponses[keyof WithdrawPackRequestResponses];

export type RequestPackParamsData = {
    body: ParamsIn;
    path: {
        /**
         * Pack
         */
        pack: string;
    };
    query?: never;
    url: '/mcp/{pack}/params';
};

export type RequestPackParamsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RequestPackParamsError = RequestPackParamsErrors[keyof RequestPackParamsErrors];

export type RequestPackParamsResponses = {
    /**
     * Successful Response
     */
    201: CatalogOut;
};

export type RequestPackParamsResponse = RequestPackParamsResponses[keyof RequestPackParamsResponses];

export type RetryPackData = {
    body: RetryIn;
    path: {
        /**
         * Pack
         */
        pack: string;
    };
    query?: never;
    url: '/mcp/{pack}/retry';
};

export type RetryPackErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RetryPackError = RetryPackErrors[keyof RetryPackErrors];

export type RetryPackResponses = {
    /**
     * Successful Response
     */
    200: CatalogOut;
};

export type RetryPackResponse = RetryPackResponses[keyof RetryPackResponses];

export type RequestPackUpdateData = {
    body: UpdateIn;
    path: {
        /**
         * Pack
         */
        pack: string;
    };
    query?: never;
    url: '/mcp/{pack}/update';
};

export type RequestPackUpdateErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RequestPackUpdateError = RequestPackUpdateErrors[keyof RequestPackUpdateErrors];

export type RequestPackUpdateResponses = {
    /**
     * Successful Response
     */
    201: CatalogOut;
};

export type RequestPackUpdateResponse = RequestPackUpdateResponses[keyof RequestPackUpdateResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/me';
};

export type MeErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * Successful Response
     */
    200: MeResponse;
};

export type MeResponse2 = MeResponses[keyof MeResponses];

export type GetModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/models';
};

export type GetModelsErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type GetModelsError = GetModelsErrors[keyof GetModelsErrors];

export type GetModelsResponses = {
    /**
     * Successful Response
     */
    200: ModelsOut;
};

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses];

export type EndSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session';
};

export type EndSessionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type EndSessionError = EndSessionErrors[keyof EndSessionErrors];

export type EndSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type EndSessionResponse = EndSessionResponses[keyof EndSessionResponses];

export type StartSessionData = {
    body: SessionIn;
    path?: never;
    query?: never;
    url: '/session';
};

export type StartSessionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type StartSessionError = StartSessionErrors[keyof StartSessionErrors];

export type StartSessionResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type StartSessionResponse = StartSessionResponses[keyof StartSessionResponses];

export type RenewSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/session/refresh';
};

export type RenewSessionErrors = {
    /**
     * Error
     */
    default: ErrorBody;
};

export type RenewSessionError = RenewSessionErrors[keyof RenewSessionErrors];

export type RenewSessionResponses = {
    /**
     * Successful Response
     */
    200: RenewedOut;
    /**
     * No session: nothing to renew
     */
    204: void;
};

export type RenewSessionResponse = RenewSessionResponses[keyof RenewSessionResponses];
