// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ActionOut
 */
export const zActionOutSchema = z.object({
    change_id: z.string().nullish(),
    result: z.enum([
        'applied',
        'proposed',
        'bootstrap'
    ])
});

/**
 * AgentBudgetOut
 */
export const zAgentBudgetOutSchema = z.object({
    agent_id: z.string(),
    limit_usd: z.string(),
    name: z.string().nullable(),
    spent_usd: z.string()
});

/**
 * AgentLimits
 *
 * Harness limits per turn. Ranges follow the Agent Builder design.
 */
export const zAgentLimitsSchema = z.object({
    max_iterations: z.int().gte(1).lte(25).optional().default(8),
    max_tokens: z.int().gte(256).lte(8192).optional().default(4096),
    max_tokens_per_call: z.int().gte(256).lte(8192).nullish(),
    temperature: z.number().gte(0).lte(1).nullish(),
    timeout_seconds: z.int().gte(10).lte(600).optional().default(120)
});

/**
 * AgentDefinition
 *
 * Content of one agent version. The agent's budget is not part of it (D22).
 */
export const zAgentDefinitionSchema = z.object({
    allowed_models: z.array(z.string().regex(/^[A-Za-z0-9][A-Za-z0-9.:_-]{0,127}$/)).max(10).optional().default([]),
    approval_tools: z.array(z.string().regex(/^[a-z0-9][a-z0-9-]{0,47}\.[A-Za-z0-9_-]{1,64}$/)).max(50).optional().default([]),
    category: z.string().optional().default(''),
    color: z.int().gte(0).lt(8).optional().default(0),
    description: z.string().optional().default(''),
    groups: z.array(z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/)).max(50).optional().default([]),
    icon: z.string().regex(/^[A-Za-z][A-Za-z0-9]{0,31}$/).optional().default('Bot'),
    limits: zAgentLimitsSchema.optional().default({
        max_iterations: 8,
        max_tokens: 4096,
        timeout_seconds: 120
    }),
    model: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9.:_-]{0,127}$/).nullish(),
    name: z.string(),
    reports_to: z.string().nullish(),
    role: z.string().optional().default(''),
    system_prompt: z.string().optional().default(''),
    tools: z.array(z.string().regex(/^[a-z0-9][a-z0-9-]{0,47}\.[A-Za-z0-9_-]{1,64}$/)).max(50).optional().default([]),
    users: z.array(z.string().regex(/^[A-Za-z0-9-]{1,64}$/)).max(50).optional().default([])
});

/**
 * AgentOut
 *
 * An agent as its users see it: no prompt and no access lists.
 */
export const zAgentOutSchema = z.object({
    allowed_models: z.array(z.string()),
    category: z.string(),
    cleanup: z.enum([
        'running',
        'done',
        'failed'
    ]).nullish(),
    color: z.int(),
    description: z.string(),
    icon: z.string(),
    id: z.string(),
    is_mine: z.boolean().optional().default(false),
    lock_version: z.int().nullable(),
    model: z.string(),
    name: z.string(),
    published_at: z.string().nullable(),
    reports_to: z.string().nullable(),
    retire_reason: z.string().nullable(),
    retired_at: z.string().nullable(),
    role: z.string(),
    status: z.string(),
    tools: z.array(z.string()),
    unavailable_tools: z.array(z.string()).optional().default([]),
    version: z.int()
});

/**
 * AgentList
 */
export const zAgentListSchema = z.object({
    items: z.array(zAgentOutSchema)
});

/**
 * AgentStateOut
 */
export const zAgentStateOutSchema = z.object({
    created_by: z.string(),
    lock_version: z.int(),
    open_version: z.int().nullable(),
    published_version: z.int().nullable(),
    status: z.string()
});

/**
 * ApproveIn
 */
export const zApproveInSchema = z.object({
    note: z.string().min(1).max(500).nullish()
});

/**
 * AuditResource
 */
export const zAuditResourceSchema = z.object({
    id: z.string(),
    type: z.string()
});

/**
 * AuditEventOut
 */
export const zAuditEventOutSchema = z.object({
    actor_email: z.string().nullish(),
    actor_is_admin: z.boolean().nullish(),
    actor_role: z.string().nullish(),
    detail: z.record(z.string(), z.unknown()),
    event: z.string(),
    event_id: z.string(),
    hash: z.string(),
    resource: zAuditResourceSchema.nullish(),
    ts: z.string(),
    user_id: z.string().nullable()
});

/**
 * AuditList
 */
export const zAuditListSchema = z.object({
    items: z.array(zAuditEventOutSchema),
    next_cursor: z.string().nullable()
});

/**
 * BudgetDefaultsIn
 */
export const zBudgetDefaultsInSchema = z.object({
    agent_monthly_usd: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    user_monthly_usd: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]),
    version: z.int().gte(0)
});

/**
 * BudgetDefaultsOut
 */
export const zBudgetDefaultsOutSchema = z.object({
    agent_monthly_usd: z.string(),
    user_monthly_usd: z.string()
});

/**
 * CatalogAgent
 */
export const zCatalogAgentSchema = z.object({
    category: z.string(),
    id: z.string(),
    name: z.string()
});

/**
 * CatalogTool
 */
export const zCatalogToolSchema = z.object({
    access: z.string(),
    audience: z.string(),
    central_groups_only: z.boolean(),
    description: z.string(),
    enabled: z.boolean().optional().default(true),
    name: z.string(),
    ref: z.string(),
    requires_service: z.string().nullish()
});

/**
 * ChangeCreatedOut
 */
export const zChangeCreatedOutSchema = z.object({
    change_id: z.string()
});

/**
 * ChangeKind
 */
export const zChangeKindSchema = z.enum([
    'enable',
    'params',
    'update'
]);

/**
 * ChatRequest
 *
 * A turn. Besides the message the client only picks the agent of a new conversation and
 * one of that agent's allowed models; everything else comes from the published version.
 */
export const zChatRequestSchema = z.object({
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/).nullish(),
    conversation_id: z.string().regex(/^[0-9a-f]{32}$/).nullish(),
    message: z.string().min(1).max(4000),
    model: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9.:_-]{0,127}$/).nullish()
});

/**
 * ConnectivityCheck
 */
export const zConnectivityCheckSchema = z.object({
    detail: z.string().max(100),
    name: z.enum([
        'broker',
        'billing_reader',
        'organizations'
    ]),
    status: z.enum(['ok', 'error'])
});

/**
 * ConnectivityOut
 */
export const zConnectivityOutSchema = z.object({
    checked_at: z.string(),
    checks: z.array(zConnectivityCheckSchema)
});

/**
 * ConversationSummary
 */
export const zConversationSummarySchema = z.object({
    agent_id: z.string(),
    conversation_id: z.string(),
    title: z.string(),
    updated_at: z.string()
});

/**
 * ConversationList
 */
export const zConversationListSchema = z.object({
    items: z.array(zConversationSummarySchema)
});

/**
 * CreateAgentIn
 */
export const zCreateAgentInSchema = z.object({
    definition: zAgentDefinitionSchema
});

/**
 * DescriptionIn
 */
export const zDescriptionInSchema = z.object({
    description: z.string().max(200),
    version: z.int().gte(0)
});

/**
 * DirectoryUserOut
 */
export const zDirectoryUserOutSchema = z.object({
    email: z.string(),
    id: z.string()
});

/**
 * DisableIn
 */
export const zDisableInSchema = z.object({
    reason: z.string().min(1).max(500),
    version: z.int().gte(0).lte(1000000)
});

/**
 * EmptyIn
 */
export const zEmptyInSchema = z.record(z.string(), z.never());

/**
 * EnableIn
 */
export const zEnableInSchema = z.object({
    config: z.record(z.string(), z.unknown()).optional().default({}),
    reason: z.string().min(1).max(500).nullish(),
    version: z.int().gte(0).lte(1000000)
});

/**
 * ErrorDetail
 */
export const zErrorDetailSchema = z.object({
    code: z.string(),
    message: z.string()
});

/**
 * ErrorBody
 */
export const zErrorBodySchema = z.object({
    error: zErrorDetailSchema
});

/**
 * FieldChange
 */
export const zFieldChangeSchema = z.object({
    after: z.union([
        z.string(),
        z.int(),
        z.number()
    ]).nullable(),
    before: z.union([
        z.string(),
        z.int(),
        z.number()
    ]).nullable(),
    field: z.string()
});

/**
 * GroupAgentOut
 */
export const zGroupAgentOutSchema = z.object({
    account_data: z.boolean(),
    id: z.string(),
    name: z.string()
});

/**
 * GroupAdminOut
 */
export const zGroupAdminOutSchema = z.object({
    agents: z.array(zGroupAgentOutSchema),
    area: z.string().nullable(),
    description: z.string(),
    fixed_type: z.boolean(),
    id: z.string(),
    system: z.boolean(),
    type: z.enum([
        'central',
        'area',
        'general'
    ]),
    version: z.int()
});

/**
 * GroupIn
 */
export const zGroupInSchema = z.object({
    group: z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/),
    reason: z.string().min(1).max(500).nullish()
});

/**
 * GroupOut
 */
export const zGroupOutSchema = z.object({
    area: z.string().nullable(),
    description: z.string(),
    id: z.string(),
    type: z.string()
});

/**
 * GroupList
 */
export const zGroupListSchema = z.object({
    items: z.array(zGroupOutSchema)
});

/**
 * GroupShapeOut
 */
export const zGroupShapeOutSchema = z.object({
    area: z.string().nullable(),
    type: z.enum([
        'central',
        'area',
        'general'
    ])
});

/**
 * GroupTargetOut
 */
export const zGroupTargetOutSchema = z.object({
    area: z.string().nullable(),
    description: z.string().nullable(),
    type: z.enum([
        'central',
        'area',
        'general'
    ])
});

/**
 * GroupChangeOut
 */
export const zGroupChangeOutSchema = z.object({
    after: zGroupTargetOutSchema.nullable(),
    agents: z.int(),
    before: zGroupShapeOutSchema.nullable(),
    change_id: z.string(),
    created_at: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    expires_at: z.string(),
    group_id: z.string(),
    kind: z.enum([
        'create',
        'update',
        'delete'
    ]),
    note: z.string().nullable(),
    proposed_by: z.string(),
    proposed_by_email: z.string().nullable(),
    reason: z.string(),
    status: z.enum([
        'pending',
        'approved',
        'rejected',
        'withdrawn',
        'expired'
    ])
});

/**
 * GroupsAdminOut
 */
export const zGroupsAdminOutSchema = z.object({
    changes: z.array(zGroupChangeOutSchema),
    items: z.array(zGroupAdminOutSchema)
});

/**
 * HashIn
 */
export const zHashInSchema = z.object({
    content_hash: z.string().regex(/^[0-9a-f]{64}$/)
});

/**
 * InstallationOut
 *
 * What was given when Mango was installed. Read only: whoever runs AWS changes it.
 */
export const zInstallationOutSchema = z.object({
    alerts_emails: z.array(z.string()),
    first_admins: z.array(z.string()),
    management_account_id: z.string().nullable(),
    name: z.string(),
    organization_id: z.string().nullable(),
    sign_up_domains: z.array(z.string()),
    version: z.string().nullable()
});

/**
 * InviteIn
 */
export const zInviteInSchema = z.object({
    email: z.string().min(3).max(254),
    groups: z.array(z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/)).max(10).optional().default([])
});

/**
 * InvitedOut
 */
export const zInvitedOutSchema = z.object({
    result: z.enum(['applied', 'bootstrap']),
    user_id: z.string()
});

/**
 * LimitsOut
 */
export const zLimitsOutSchema = z.object({
    max_iterations: z.int(),
    max_tokens: z.int(),
    max_tokens_per_call: z.int().nullable(),
    temperature: z.number().nullable(),
    timeout_seconds: z.int()
});

/**
 * DefinitionOut
 */
export const zDefinitionOutSchema = z.object({
    allowed_models: z.array(z.string()),
    approval_tools: z.array(z.string()),
    category: z.string(),
    color: z.int(),
    description: z.string(),
    groups: z.array(z.string()),
    icon: z.string(),
    limits: zLimitsOutSchema,
    model: z.string().nullable(),
    name: z.string(),
    reports_to: z.string().nullable(),
    role: z.string(),
    system_prompt: z.string(),
    tools: z.array(z.string()),
    users: z.array(z.string())
});

/**
 * MeCan
 *
 * Hints for the SPA only; the API authorizes every request on its own.
 */
export const zMeCanSchema = z.object({
    create_agent: z.boolean()
});

/**
 * MeResponse
 */
export const zMeResponseSchema = z.object({
    business_unit: z.string().nullable(),
    can: zMeCanSchema,
    email: z.string().nullable(),
    groups: z.array(z.string()),
    is_admin: z.boolean(),
    name: z.string().nullable(),
    role: z.string().nullable(),
    user_id: z.string()
});

/**
 * MemberAccountOut
 */
export const zMemberAccountOutSchema = z.object({
    account_id: z.string(),
    name: z.string(),
    status: z.enum([
        'ok',
        'role_missing',
        'identity_not_required'
    ])
});

/**
 * MemberAccessOut
 */
export const zMemberAccessOutSchema = z.object({
    accounts: z.array(zMemberAccountOutSchema),
    checked_at: z.string(),
    identity_required: z.boolean().nullable(),
    total: z.int(),
    truncated: z.boolean()
});

/**
 * ModelAgentOut
 */
export const zModelAgentOutSchema = z.object({
    category: z.string(),
    id: z.string(),
    name: z.string()
});

/**
 * AdminModelOut
 */
export const zAdminModelOutSchema = z.object({
    agents: z.array(zModelAgentOutSchema),
    cache_read_usd: z.string().nullable(),
    cache_write_usd: z.string().nullable(),
    confirmed_at: z.string().nullable(),
    confirmed_by: z.string().nullable(),
    context_tokens: z.int().nullable(),
    disabled_at: z.string().nullable(),
    disabled_by: z.string().nullable(),
    disabled_reason: z.string().nullable(),
    id: z.string(),
    input_usd: z.string().nullable(),
    is_default: z.boolean(),
    list_input_usd: z.string().nullable(),
    list_output_usd: z.string().nullable(),
    name: z.string(),
    output_usd: z.string().nullable(),
    provider: z.string(),
    status: z.enum([
        'enabled',
        'available',
        'disabled',
        'noaccess'
    ]),
    supports_tools: z.boolean(),
    supports_vision: z.boolean()
});

/**
 * AdminModelsOut
 */
export const zAdminModelsOutSchema = z.object({
    items: z.array(zAdminModelOutSchema),
    refreshed_at: z.string().nullable(),
    region: z.string(),
    version: z.int()
});

/**
 * ModelOut
 */
export const zModelOutSchema = z.object({
    context_tokens: z.int().nullable(),
    id: z.string(),
    input_usd: z.string(),
    name: z.string(),
    output_usd: z.string(),
    provider: z.string(),
    supports_tools: z.boolean()
});

/**
 * ModelUpdateIn
 *
 * Enable a model (or change the prices of an enabled one), or disable it.
 */
export const zModelUpdateInSchema = z.object({
    enabled: z.boolean(),
    input_usd: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    output_usd: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullish(),
    reason: z.string().nullish(),
    version: z.int().gte(1)
});

/**
 * ModelsOut
 */
export const zModelsOutSchema = z.object({
    items: z.array(zModelOutSchema),
    version: z.int()
});

/**
 * OptionalReasonIn
 */
export const zOptionalReasonInSchema = z.object({
    reason: z.string().min(1).max(500).nullish()
});

/**
 * OrgNode
 */
export const zOrgNodeSchema = z.object({
    category: z.string(),
    color: z.int(),
    description: z.string(),
    icon: z.string(),
    id: z.string(),
    name: z.string(),
    reports_to: z.string().nullable(),
    role: z.string(),
    version: z.int()
});

/**
 * OrgOut
 */
export const zOrgOutSchema = z.object({
    nodes: z.array(zOrgNodeSchema),
    root: z.string()
});

/**
 * OrganizationalUnit
 */
export const zOrganizationalUnitSchema = z.object({
    id: z.string().regex(/^ou-[0-9a-z]{4,32}-[0-9a-z]{8,32}$/),
    name: z.string().min(1).max(128),
    parent_id: z.string().regex(/^(r-[0-9a-z]{4,32}|ou-[0-9a-z]{4,32}-[0-9a-z]{8,32})$/),
    path: z.array(z.string().min(1).max(128)).min(1).max(5)
});

/**
 * OrganizationOut
 */
export const zOrganizationOutSchema = z.object({
    ous: z.array(zOrganizationalUnitSchema)
});

/**
 * PackDecision
 */
export const zPackDecisionSchema = z.object({
    change_id: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    kind: zChangeKindSchema,
    reason: z.string().nullable()
});

/**
 * PackParam
 */
export const zPackParamSchema = z.object({
    allowed: z.array(z.string()),
    default: z.string(),
    description: z.string().nullable(),
    key: z.string(),
    value: z.string().nullable()
});

/**
 * PackRequest
 */
export const zPackRequestSchema = z.object({
    change_id: z.string(),
    config: z.record(z.string(), z.string()),
    created_at: z.string(),
    expires_at: z.string(),
    kind: zChangeKindSchema,
    own: z.boolean(),
    pack_version: z.string(),
    reason: z.string().nullable(),
    requested_by: z.string(),
    requested_by_email: z.string().nullable()
});

/**
 * PackUpdate
 *
 * What moving from the installed version to the release's version changes.
 */
export const zPackUpdateSchema = z.object({
    added_permissions: z.array(z.string()),
    added_tools: z.array(z.string()),
    removed_permissions: z.array(z.string()),
    removed_tools: z.array(z.string()),
    version: z.string()
});

/**
 * PackOut
 */
export const zPackOutSchema = z.object({
    approved_at: z.string().nullish(),
    approved_by: z.string().nullish(),
    approved_by_email: z.string().nullish(),
    disable_reason: z.string().nullish(),
    disabled_at: z.string().nullish(),
    disabled_by: z.string().nullish(),
    disabled_by_email: z.string().nullish(),
    failed_step: z.string().nullish(),
    failure: z.string().nullish(),
    installed_version: z.string().nullable(),
    last_rejected: zPackDecisionSchema.nullish(),
    lock_version: z.int(),
    params: z.array(zPackParamSchema),
    pending: zPackRequestSchema.nullish(),
    requested_at: z.string().nullish(),
    requested_by: z.string().nullish(),
    requested_by_email: z.string().nullish(),
    status: z.enum([
        'available',
        'pending',
        'installing',
        'enabled',
        'error',
        'disabling',
        'disabled'
    ]),
    status_at: z.string().nullish(),
    update: zPackUpdateSchema.nullable(),
    version: z.string()
});

/**
 * CatalogConnector
 */
export const zCatalogConnectorSchema = z.object({
    agents: z.array(zCatalogAgentSchema).optional().default([]),
    data_tier: z.string(),
    description: z.string(),
    enabled: z.boolean(),
    id: z.string(),
    identity_mode: z.string(),
    kind: z.string(),
    name: z.string(),
    pack: zPackOutSchema.nullish(),
    permissions: z.array(z.string()),
    provider: z.string(),
    tools: z.array(zCatalogToolSchema)
});

/**
 * CatalogOut
 */
export const zCatalogOutSchema = z.object({
    items: z.array(zCatalogConnectorSchema),
    max_enabled_packs: z.int().optional().default(10)
});

/**
 * ParamsIn
 */
export const zParamsInSchema = z.object({
    config: z.record(z.string(), z.unknown()),
    version: z.int().gte(0).lte(1000000)
});

/**
 * PersonOut
 */
export const zPersonOutSchema = z.object({
    created_at: z.string(),
    email: z.string(),
    groups: z.array(z.string()),
    mfa: z.boolean(),
    status: z.enum([
        'active',
        'invited',
        'disabled'
    ]),
    user_id: z.string()
});

/**
 * PeopleOut
 */
export const zPeopleOutSchema = z.object({
    admins: z.int(),
    incomplete: z.boolean(),
    items: z.array(zPersonOutSchema),
    next_cursor: z.string().nullable(),
    pending: z.int(),
    with_access: z.int()
});

/**
 * PolicyRule
 *
 * A policy as shown: only the threshold of its condition is set.
 */
export const zPolicyRuleSchema = z.object({
    amount_usd: z.string().regex(/^\d{1,9}(\.\d{1,2})?$/).nullish(),
    approvers: z.int().gte(1).lte(3),
    condition: z.enum([
        'always',
        'amount',
        'count',
        'environment'
    ]),
    count: z.int().gte(1).lte(100000).nullish(),
    environment: z.enum(['prod', 'staging']).nullish(),
    expires_hours: z.union([
        z.literal(1),
        z.literal(4),
        z.literal(24),
        z.literal(48),
        z.literal(72)
    ])
});

/**
 * PolicyChangeOut
 */
export const zPolicyChangeOutSchema = z.object({
    after: zPolicyRuleSchema,
    before: zPolicyRuleSchema,
    change_id: z.string(),
    created_at: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    expires_at: z.string(),
    note: z.string().nullable(),
    proposed_by: z.string(),
    proposed_by_email: z.string().nullable(),
    reason: z.string(),
    status: z.enum([
        'pending',
        'approved',
        'rejected',
        'withdrawn',
        'expired'
    ]),
    tool: z.string()
});

/**
 * PromptLine
 */
export const zPromptLineSchema = z.object({
    op: z.enum([
        '+',
        '-',
        ' '
    ]),
    text: z.string()
});

/**
 * ProposalIn
 */
export const zProposalInSchema = z.object({
    base_version: z.int().gte(0),
    reason: z.string().min(1).max(500),
    units: z.record(z.string(), z.unknown())
});

/**
 * QuotasOut
 */
export const zQuotasOutSchema = z.object({
    drafts: z.int(),
    max_drafts: z.int(),
    max_submissions_per_day: z.int(),
    submissions_today: z.int()
});

/**
 * ReasonIn
 */
export const zReasonInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * ResetCreatedOut
 */
export const zResetCreatedOutSchema = z.object({
    change_id: z.string()
});

/**
 * ResetOut
 */
export const zResetOutSchema = z.object({
    change_id: z.string(),
    created_at: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    expires_at: z.string(),
    identity_verified: z.boolean(),
    note: z.string().nullable(),
    proposed_by: z.string(),
    proposed_by_email: z.string().nullable(),
    reason: z.string(),
    status: z.enum([
        'pending',
        'approved',
        'rejected',
        'withdrawn',
        'expired'
    ]),
    target_email: z.string().nullable(),
    target_user: z.string()
});

/**
 * ResetListOut
 */
export const zResetListOutSchema = z.object({
    items: z.array(zResetOutSchema)
});

/**
 * ResolveIn
 */
export const zResolveInSchema = z.object({
    emails: z.array(z.string().max(254)).max(20).optional().default([]),
    ids: z.array(z.string().regex(/^[A-Za-z0-9-]{1,64}$/)).max(50).optional().default([])
});

/**
 * ResolveOut
 */
export const zResolveOutSchema = z.object({
    emails_not_found: z.array(z.string()),
    ids_not_found: z.array(z.string()),
    users: z.array(zDirectoryUserOutSchema)
});

/**
 * RetireIn
 */
export const zRetireInSchema = z.object({
    lock_version: z.int().gte(1),
    reason: z.string().min(1).max(500)
});

/**
 * RetryIn
 */
export const zRetryInSchema = z.object({
    version: z.int().gte(0).lte(1000000)
});

/**
 * ReviewOut
 */
export const zReviewOutSchema = z.object({
    agent_id: z.string(),
    approved_at: z.string().nullable(),
    approved_by: z.string().nullable(),
    approved_by_email: z.string().nullable(),
    category: z.string(),
    changes: z.int().nullable(),
    color: z.int(),
    content_hash: z.string().nullable(),
    created_by: z.string(),
    created_by_email: z.string().nullable(),
    decided_at: z.string().nullable(),
    description: z.string(),
    failed_step: z.string().nullable(),
    icon: z.string(),
    is_author: z.boolean(),
    kind: z.enum(['new', 'change']),
    name: z.string(),
    published_at: z.string().nullable(),
    rejected_at: z.string().nullable(),
    rejected_by: z.string().nullable(),
    rejected_by_email: z.string().nullable(),
    rejection_reason: z.string().nullable(),
    retire_reason: z.string().nullable(),
    retired_at: z.string().nullable(),
    retired_by: z.string().nullable(),
    retired_by_email: z.string().nullable(),
    retryable: z.boolean(),
    status: z.string(),
    submitted_at: z.string().nullable(),
    version: z.int()
});

/**
 * ReviewsOut
 */
export const zReviewsOutSchema = z.object({
    history: z.array(zReviewOutSchema),
    queue: z.array(zReviewOutSchema)
});

/**
 * RuleOut
 *
 * The policy the request was born with and why it fell in its tier.
 */
export const zRuleOutSchema = z.object({
    amount_usd: z.string().nullish(),
    approvers: z.int(),
    condition: z.enum([
        'always',
        'amount',
        'count',
        'environment'
    ]),
    count: z.int().nullish(),
    environment: z.string().nullish(),
    expires_hours: z.int(),
    reason: z.enum([
        'always',
        'above',
        'below',
        'unknown'
    ])
});

/**
 * SaveDraftIn
 */
export const zSaveDraftInSchema = z.object({
    definition: zAgentDefinitionSchema,
    revision: z.int().gte(1).lte(1000000)
});

/**
 * SearchIn
 */
export const zSearchInSchema = z.object({
    cursor: z.string().regex(/^[0-9]{1,5}$/).nullish(),
    filter: z.enum([
        'all',
        'pending',
        'invited',
        'disabled'
    ]).optional().default('all'),
    prefix: z.string().nullish()
});

/**
 * SetChange
 */
export const zSetChangeSchema = z.object({
    added: z.array(z.string()),
    field: z.string(),
    removed: z.array(z.string())
});

/**
 * DiffOut
 *
 * Changes of a version against the published one, computed here (never by the SPA).
 */
export const zDiffOutSchema = z.object({
    changes: z.int(),
    fields: z.array(zFieldChangeSchema),
    is_new: z.boolean(),
    prompt: z.array(zPromptLineSchema).nullable(),
    sets: z.array(zSetChangeSchema)
});

/**
 * SignatureOut
 */
export const zSignatureOutSchema = z.object({
    at: z.string(),
    email: z.string().nullable(),
    note: z.string().nullable(),
    user_id: z.string()
});

/**
 * ApprovalOut
 */
export const zApprovalOutSchema = z.object({
    agent_id: z.string(),
    agent_name: z.string().nullable(),
    approval_id: z.string(),
    approvals_needed: z.int(),
    arguments: z.record(z.string(), z.unknown()),
    can_sign: z.boolean(),
    conversation_id: z.string().nullable(),
    created_at: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    description: z.string(),
    error: z.string().nullable(),
    executed_at: z.string().nullable(),
    expires_at: z.string(),
    mine: z.boolean(),
    note: z.string().nullable(),
    requested_by: z.string(),
    requested_by_email: z.string().nullable(),
    rule: zRuleOutSchema,
    server_name: z.string(),
    signatures: z.array(zSignatureOutSchema),
    status: z.enum([
        'pending',
        'approved',
        'executing',
        'executed',
        'failed',
        'rejected',
        'cancelled',
        'expired'
    ]),
    tier: z.enum(['self', 'approvers']),
    tool: z.string()
});

/**
 * ApprovalListOut
 */
export const zApprovalListOutSchema = z.object({
    can_decide: z.boolean(),
    items: z.array(zApprovalOutSchema)
});

/**
 * SubmitIn
 */
export const zSubmitInSchema = z.object({
    revision: z.int().gte(1).lte(1000000)
});

/**
 * ToolPolicyOut
 */
export const zToolPolicyOutSchema = z.object({
    conditions: z.array(z.enum([
        'always',
        'amount',
        'count',
        'environment'
    ])),
    description: z.string(),
    pending_change_id: z.string().nullable(),
    policy: zPolicyRuleSchema,
    server_name: z.string(),
    tool: z.string(),
    version: z.int()
});

/**
 * PoliciesOut
 */
export const zPoliciesOutSchema = z.object({
    changes: z.array(zPolicyChangeOutSchema),
    tools: z.array(zToolPolicyOutSchema)
});

/**
 * ToolStatus
 */
export const zToolStatusSchema = z.object({
    name: z.string(),
    status: z.string()
});

/**
 * MessageOut
 */
export const zMessageOutSchema = z.object({
    approvals: z.array(z.string()).optional().default([]),
    content: z.string(),
    created_at: z.string(),
    message_id: z.string(),
    role: z.string(),
    tools: z.array(zToolStatusSchema)
});

/**
 * ConversationDetail
 */
export const zConversationDetailSchema = z.object({
    agent_id: z.string(),
    approvals: z.array(zApprovalOutSchema).optional().default([]),
    conversation_id: z.string(),
    messages: z.array(zMessageOutSchema),
    title: z.string()
});

/**
 * UpdateIn
 */
export const zUpdateInSchema = z.object({
    config: z.record(z.string(), z.unknown()).nullish(),
    version: z.int().gte(0).lte(1000000)
});

/**
 * UserBudgetIn
 */
export const zUserBudgetInSchema = z.object({
    limit_usd: z.union([
        z.number(),
        z.string().regex(/^(?!^[-+.]*$)[+-]?0*\d*\.?\d*$/)
    ]).nullable(),
    version: z.int().gte(0)
});

/**
 * UserBudgetOut
 */
export const zUserBudgetOutSchema = z.object({
    email: z.string().nullable(),
    limit_usd: z.string(),
    override: z.boolean(),
    spent_usd: z.string(),
    user_id: z.string()
});

/**
 * BudgetsOut
 */
export const zBudgetsOutSchema = z.object({
    agents: z.array(zAgentBudgetOutSchema),
    defaults: zBudgetDefaultsOutSchema,
    period: z.string(),
    users: z.array(zUserBudgetOutSchema),
    version: z.int()
});

/**
 * VersionSummary
 */
export const zVersionSummarySchema = z.object({
    agent_id: z.string(),
    base_version: z.int().nullable(),
    category: z.string(),
    color: z.int(),
    created_at: z.string(),
    description: z.string(),
    failed_step: z.string().nullable(),
    icon: z.string(),
    name: z.string(),
    rejected_at: z.string().nullable(),
    rejection_reason: z.string().nullable(),
    revision: z.int(),
    status: z.string(),
    submitted_at: z.string().nullable(),
    updated_at: z.string(),
    version: z.int()
});

/**
 * MineOut
 */
export const zMineOutSchema = z.object({
    items: z.array(zVersionSummarySchema),
    quotas: zQuotasOutSchema
});

/**
 * ViolationOut
 */
export const zViolationOutSchema = z.object({
    code: z.string(),
    field: z.string(),
    items: z.array(z.string())
});

/**
 * VersionOut
 */
export const zVersionOutSchema = z.object({
    agent: zAgentStateOutSchema,
    agent_id: z.string(),
    approved_at: z.string().nullable(),
    approved_by: z.string().nullable(),
    approved_by_email: z.string().nullable(),
    base: zDefinitionOutSchema.nullable(),
    base_version: z.int().nullable(),
    content_hash: z.string().nullable(),
    created_at: z.string(),
    created_by: z.string(),
    created_by_email: z.string().nullable(),
    definition: zDefinitionOutSchema,
    diff: zDiffOutSchema,
    failed_step: z.string().nullable(),
    failure: z.string().nullable(),
    is_author: z.boolean(),
    published_at: z.string().nullable(),
    rejected_at: z.string().nullable(),
    rejected_by: z.string().nullable(),
    rejected_by_email: z.string().nullable(),
    rejection_reason: z.string().nullable(),
    revision: z.int(),
    status: z.string(),
    submitted_at: z.string().nullable(),
    submitted_by: z.string().nullable(),
    updated_at: z.string(),
    version: z.int(),
    violations: z.array(zViolationOutSchema).nullable()
});

/**
 * ChangeOut
 */
export const zMangoApiAdminChangeOutSchema = z.object({
    base_version: z.int(),
    change_id: z.string(),
    created_at: z.string(),
    expires_at: z.string(),
    proposed_by: z.string(),
    proposed_by_email: z.string().nullable(),
    reason: z.string(),
    units: z.record(z.string(), z.array(z.string()))
});

/**
 * BusinessUnitsOut
 */
export const zBusinessUnitsOutSchema = z.object({
    pending: z.array(zMangoApiAdminChangeOutSchema),
    units: z.record(z.string(), z.array(z.string())),
    version: z.int()
});

/**
 * RejectIn
 */
export const zMangoApiAdminRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * RejectIn
 */
export const zMangoApiAgentsRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * RejectIn
 */
export const zMangoApiApprovalsRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * ProposeIn
 */
export const zMangoApiGroupAdminProposeInSchema = z.object({
    area: z.string().regex(/^[a-z0-9-]{2,32}$/).nullish(),
    base_version: z.int().gte(0).nullish(),
    description: z.string().max(200).nullish(),
    group_id: z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/),
    kind: z.enum([
        'create',
        'update',
        'delete'
    ]),
    reason: z.string().min(1).max(500),
    type: z.enum([
        'central',
        'area',
        'general'
    ]).nullish()
});

/**
 * RejectIn
 */
export const zMangoApiGroupAdminRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * RejectIn
 */
export const zMangoApiMcpRejectInSchema = z.object({
    reason: z.string().min(1).max(500).nullish()
});

/**
 * ProposeIn
 */
export const zMangoApiMfaResetProposeInSchema = z.object({
    email: z.string().max(254),
    identity_verified: z.literal(true),
    reason: z.string().min(1).max(500)
});

/**
 * RejectIn
 */
export const zMangoApiMfaResetRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * ChangeOut
 */
export const zMangoApiPeopleChangeOutSchema = z.object({
    change_id: z.string(),
    created_at: z.string(),
    decided_at: z.string().nullable(),
    decided_by: z.string().nullable(),
    decided_by_email: z.string().nullable(),
    expires_at: z.string(),
    group: z.string().nullable(),
    kind: z.enum([
        'add',
        'remove',
        'disable',
        'enable'
    ]),
    note: z.string().nullable(),
    proposed_by: z.string(),
    proposed_by_email: z.string().nullable(),
    reason: z.string(),
    status: z.enum([
        'pending',
        'approved',
        'rejected',
        'withdrawn',
        'expired'
    ]),
    target_email: z.string(),
    target_user: z.string()
});

/**
 * ChangeListOut
 */
export const zChangeListOutSchema = z.object({
    items: z.array(zMangoApiPeopleChangeOutSchema)
});

/**
 * ProposeIn
 */
export const zMangoApiToolPoliciesProposeInSchema = z.object({
    amount_usd: z.string().regex(/^\d{1,9}(\.\d{1,2})?$/).nullish(),
    approvers: z.int().gte(1).lte(3),
    base_version: z.int().gte(0).lte(1000000),
    condition: z.enum([
        'always',
        'amount',
        'count',
        'environment'
    ]),
    count: z.int().gte(1).lte(100000).nullish(),
    environment: z.enum(['prod', 'staging']).nullish(),
    expires_hours: z.union([
        z.literal(1),
        z.literal(4),
        z.literal(24),
        z.literal(48),
        z.literal(72)
    ]),
    reason: z.string().min(1).max(500)
});

/**
 * RejectIn
 */
export const zMangoApiToolPoliciesRejectInSchema = z.object({
    reason: z.string().min(1).max(500)
});

export const zAdminAuditQuery = z.object({
    limit: z.int().gte(1).lte(200).optional().default(50),
    cursor: z.string().max(128).nullish(),
    since: z.iso.datetime().nullish(),
    until: z.iso.datetime().nullish(),
    exclude: z.array(z.literal('reads')).max(1).optional().default([]),
    event: z.string().max(64).regex(/^[a-z][a-z_]*(\.[a-z_]+)*\.?$/).nullish()
});

/**
 * Successful Response
 */
export const zAdminAuditResponse = zAuditListSchema;

/**
 * Successful Response
 */
export const zGetBudgetsResponse = zBudgetsOutSchema;

export const zPutDefaultsBody = zBudgetDefaultsInSchema;

/**
 * Successful Response
 */
export const zPutDefaultsResponse = zBudgetsOutSchema;

export const zPutUserBudgetBody = zUserBudgetInSchema;

export const zPutUserBudgetPath = z.object({
    user_id: z.string().regex(/^[A-Za-z0-9-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zPutUserBudgetResponse = zBudgetsOutSchema;

/**
 * Successful Response
 */
export const zGetBusinessUnitsResponse = zBusinessUnitsOutSchema;

export const zPostChangeBody = zProposalInSchema;

/**
 * Successful Response
 */
export const zPostChangeResponse = zChangeCreatedOutSchema;

export const zApproveChangeBody = zEmptyInSchema;

export const zApproveChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveChangeResponse = zBusinessUnitsOutSchema;

export const zRejectChangeBody = zMangoApiAdminRejectInSchema;

export const zRejectChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectChangeResponse = zBusinessUnitsOutSchema;

export const zWithdrawChangeBody = zEmptyInSchema;

export const zWithdrawChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawChangeResponse = zBusinessUnitsOutSchema;

export const zConnectivityCheckBody = zEmptyInSchema;

/**
 * Successful Response
 */
export const zConnectivityCheckResponse = zConnectivityOutSchema;

/**
 * Successful Response
 */
export const zGetAdminGroupsResponse = zGroupsAdminOutSchema;

export const zPostGroupChangeBody = zMangoApiGroupAdminProposeInSchema;

/**
 * Successful Response
 */
export const zPostGroupChangeResponse = zChangeCreatedOutSchema;

export const zApproveGroupChangeBody = zEmptyInSchema;

export const zApproveGroupChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveGroupChangeResponse = zGroupsAdminOutSchema;

export const zRejectGroupChangeBody = zMangoApiGroupAdminRejectInSchema;

export const zRejectGroupChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectGroupChangeResponse = zGroupsAdminOutSchema;

export const zWithdrawGroupChangeBody = zEmptyInSchema;

export const zWithdrawGroupChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawGroupChangeResponse = zGroupsAdminOutSchema;

export const zPutGroupDescriptionBody = zDescriptionInSchema;

export const zPutGroupDescriptionPath = z.object({
    group_id: z.string().regex(/^[a-z0-9][a-z0-9-]{1,63}$/)
});

/**
 * Successful Response
 */
export const zPutGroupDescriptionResponse = zGroupsAdminOutSchema;

/**
 * Successful Response
 */
export const zGetInstallationResponse = zInstallationOutSchema;

export const zMemberAccessCheckBody = zEmptyInSchema;

/**
 * Successful Response
 */
export const zMemberAccessCheckResponse = zMemberAccessOutSchema;

/**
 * Successful Response
 */
export const zGetRequestsResponse = zResetListOutSchema;

export const zPostRequestBody = zMangoApiMfaResetProposeInSchema;

/**
 * Successful Response
 */
export const zPostRequestResponse = zResetCreatedOutSchema;

export const zApproveRequestBody = zEmptyInSchema;

export const zApproveRequestPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveRequestResponse = zResetListOutSchema;

export const zRejectRequestBody = zMangoApiMfaResetRejectInSchema;

export const zRejectRequestPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectRequestResponse = zResetListOutSchema;

export const zWithdrawRequestBody = zEmptyInSchema;

export const zWithdrawRequestPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawRequestResponse = zResetListOutSchema;

/**
 * Successful Response
 */
export const zGetAdminModelsResponse = zAdminModelsOutSchema;

export const zRefreshAdminModelsBody = zEmptyInSchema;

/**
 * Successful Response
 */
export const zRefreshAdminModelsResponse = zAdminModelsOutSchema;

export const zPutAdminModelBody = zModelUpdateInSchema;

export const zPutAdminModelPath = z.object({
    model_id: z.string().regex(/^[A-Za-z0-9][A-Za-z0-9.:_-]{0,127}$/)
});

/**
 * Successful Response
 */
export const zPutAdminModelResponse = zAdminModelsOutSchema;

/**
 * Successful Response
 */
export const zGetOrganizationResponse = zOrganizationOutSchema;

/**
 * Successful Response
 */
export const zGetMemberChangesResponse = zChangeListOutSchema;

export const zApproveMemberChangeBody = zEmptyInSchema;

export const zApproveMemberChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveMemberChangeResponse = zChangeListOutSchema;

export const zRejectMemberChangeBody = zReasonInSchema;

export const zRejectMemberChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectMemberChangeResponse = zChangeListOutSchema;

export const zWithdrawMemberChangeBody = zEmptyInSchema;

export const zWithdrawMemberChangePath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawMemberChangeResponse = zChangeListOutSchema;

export const zInvitePersonBody = zInviteInSchema;

/**
 * Successful Response
 */
export const zInvitePersonResponse = zInvitedOutSchema;

export const zSearchPeopleBody = zSearchInSchema;

/**
 * Successful Response
 */
export const zSearchPeopleResponse = zPeopleOutSchema;

export const zDisablePersonBody = zReasonInSchema;

export const zDisablePersonPath = z.object({
    user_id: z.string().regex(/^[A-Za-z0-9-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zDisablePersonResponse = zActionOutSchema;

export const zEnablePersonBody = zOptionalReasonInSchema;

export const zEnablePersonPath = z.object({
    user_id: z.string().regex(/^[A-Za-z0-9-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zEnablePersonResponse = zActionOutSchema;

export const zAddGroupBody = zGroupInSchema;

export const zAddGroupPath = z.object({
    user_id: z.string().regex(/^[A-Za-z0-9-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zAddGroupResponse = zActionOutSchema;

export const zRemoveGroupBody = zGroupInSchema;

export const zRemoveGroupPath = z.object({
    user_id: z.string().regex(/^[A-Za-z0-9-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zRemoveGroupResponse = zActionOutSchema;

/**
 * Successful Response
 */
export const zGetAgentsResponse = zAgentListSchema;

export const zPostAgentBody = zCreateAgentInSchema;

/**
 * Successful Response
 */
export const zPostAgentResponse = zVersionOutSchema;

/**
 * Successful Response
 */
export const zGetMineResponse = zMineOutSchema;

/**
 * Successful Response
 */
export const zGetOrgResponse = zOrgOutSchema;

/**
 * Successful Response
 */
export const zGetReviewsResponse = zReviewsOutSchema;

export const zGetAgentPath = z.object({
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zGetAgentResponse = zAgentOutSchema;

export const zRetireAgentBody = zRetireInSchema;

export const zRetireAgentPath = z.object({
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zRetireAgentResponse = zAgentOutSchema;

export const zPostVersionBody = zEmptyInSchema;

export const zPostVersionPath = z.object({
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zPostVersionResponse = zVersionOutSchema;

export const zDeleteVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

export const zDeleteVersionQuery = z.object({
    revision: z.int().gte(1).lte(1000000)
});

/**
 * Successful Response
 */
export const zDeleteVersionResponse = z.void();

export const zReadVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zReadVersionResponse = zVersionOutSchema;

export const zPutVersionBody = zSaveDraftInSchema;

export const zPutVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zPutVersionResponse = zVersionOutSchema;

export const zApproveVersionBody = zHashInSchema;

export const zApproveVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zApproveVersionResponse = zVersionOutSchema;

export const zRejectVersionBody = zMangoApiAgentsRejectInSchema;

export const zRejectVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zRejectVersionResponse = zVersionOutSchema;

export const zReopenVersionBody = zEmptyInSchema;

export const zReopenVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zReopenVersionResponse = zVersionOutSchema;

export const zRetryVersionBody = zHashInSchema;

export const zRetryVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zRetryVersionResponse = zVersionOutSchema;

export const zSubmitVersionBody = zSubmitInSchema;

export const zSubmitVersionPath = z.object({
    version: z.int().gte(1).lte(999999),
    agent_id: z.string().regex(/^(?:[a-z2-7]{16}|[a-z][a-z0-9]{1,15})$/)
});

/**
 * Successful Response
 */
export const zSubmitVersionResponse = zVersionOutSchema;

export const zListApprovalsQuery = z.object({
    view: z.enum(['pending', 'resolved']).optional().default('pending'),
    conversation_id: z.string().regex(/^[0-9a-f]{32}$/).nullish()
});

/**
 * Successful Response
 */
export const zListApprovalsResponse = zApprovalListOutSchema;

/**
 * Successful Response
 */
export const zGetToolPoliciesResponse = zPoliciesOutSchema;

export const zApproveToolPolicyBody = zEmptyInSchema;

export const zApproveToolPolicyPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveToolPolicyResponse = zPoliciesOutSchema;

export const zRejectToolPolicyBody = zMangoApiToolPoliciesRejectInSchema;

export const zRejectToolPolicyPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectToolPolicyResponse = zPoliciesOutSchema;

export const zWithdrawToolPolicyBody = zEmptyInSchema;

export const zWithdrawToolPolicyPath = z.object({
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawToolPolicyResponse = zPoliciesOutSchema;

export const zProposeToolPolicyBody = zMangoApiToolPoliciesProposeInSchema;

export const zProposeToolPolicyPath = z.object({
    tool: z.string().max(113).regex(/^[a-z0-9][a-z0-9-]{0,47}\.[A-Za-z0-9_-]{1,64}$/)
});

/**
 * Successful Response
 */
export const zProposeToolPolicyResponse = zChangeCreatedOutSchema;

export const zGetApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zGetApprovalResponse = zApprovalOutSchema;

export const zApproveApprovalBody = zApproveInSchema;

export const zApproveApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApproveApprovalResponse = zApprovalOutSchema;

export const zCancelApprovalBody = zEmptyInSchema;

export const zCancelApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zCancelApprovalResponse = zApprovalOutSchema;

export const zConfirmApprovalBody = zEmptyInSchema;

export const zConfirmApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zConfirmApprovalResponse = zApprovalOutSchema;

export const zExecuteApprovalBody = zEmptyInSchema;

export const zExecuteApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zExecuteApprovalResponse = zApprovalOutSchema;

export const zRejectApprovalBody = zMangoApiApprovalsRejectInSchema;

export const zRejectApprovalPath = z.object({
    approval_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectApprovalResponse = zApprovalOutSchema;

export const zChatBody = zChatRequestSchema;

/**
 * Successful Response
 */
export const zListConversationsResponse = zConversationListSchema;

export const zGetConversationPath = z.object({
    conversation_id: z.string()
});

/**
 * Successful Response
 */
export const zGetConversationResponse = zConversationDetailSchema;

export const zResolveUsersBody = zResolveInSchema;

/**
 * Successful Response
 */
export const zResolveUsersResponse = zResolveOutSchema;

/**
 * Successful Response
 */
export const zListGroupsResponse = zGroupListSchema;

/**
 * Response Health Api Health Get
 *
 * Successful Response
 */
export const zHealthResponse = z.record(z.string(), z.string());

/**
 * Successful Response
 */
export const zGetCatalogResponse = zCatalogOutSchema;

export const zDisablePackBody = zDisableInSchema;

export const zDisablePackPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/)
});

/**
 * Successful Response
 */
export const zDisablePackResponse = zCatalogOutSchema;

export const zRequestPackEnablementBody = zEnableInSchema;

export const zRequestPackEnablementPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/)
});

/**
 * Successful Response
 */
export const zRequestPackEnablementResponse = zCatalogOutSchema;

export const zApprovePackRequestBody = zEmptyInSchema;

export const zApprovePackRequestPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/),
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zApprovePackRequestResponse = zCatalogOutSchema;

export const zRejectPackRequestBody = zMangoApiMcpRejectInSchema;

export const zRejectPackRequestPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/),
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zRejectPackRequestResponse = zCatalogOutSchema;

export const zWithdrawPackRequestBody = zEmptyInSchema;

export const zWithdrawPackRequestPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/),
    change_id: z.string().regex(/^[0-9a-f]{32}$/)
});

/**
 * Successful Response
 */
export const zWithdrawPackRequestResponse = zCatalogOutSchema;

export const zRequestPackParamsBody = zParamsInSchema;

export const zRequestPackParamsPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/)
});

/**
 * Successful Response
 */
export const zRequestPackParamsResponse = zCatalogOutSchema;

export const zRetryPackBody = zRetryInSchema;

export const zRetryPackPath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/)
});

/**
 * Successful Response
 */
export const zRetryPackResponse = zCatalogOutSchema;

export const zRequestPackUpdateBody = zUpdateInSchema;

export const zRequestPackUpdatePath = z.object({
    pack: z.string().max(24).regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/)
});

/**
 * Successful Response
 */
export const zRequestPackUpdateResponse = zCatalogOutSchema;

/**
 * Successful Response
 */
export const zMeResponse = zMeResponseSchema;

/**
 * Successful Response
 */
export const zGetModelsResponse = zModelsOutSchema;
